import { test } from 'node:test';
import assert from 'node:assert/strict';
import { detectCommitAI } from '../src/lib/github-ai.ts';
import { githubCommitCsv, mergeGitHubAnalysis } from '../src/lib/github-analytics.ts';

const human = { key: 'github:alice', name: 'Alice', login: 'alice', email: 'alice@example.test', url: 'https://github.com/alice' };
const commit = (message, extra = {}) => ({ sha: 'a'.repeat(40), message, author: human, committer: human, authoredAt: '2026-01-01T00:00:00Z', committedAt: '2026-01-02T00:00:00Z', parents: [], verified: false, url: 'https://github.com/team/repo/commit/a', ...extra });

test('AI co-author trailers identify declared tools and preserve the evidence', () => {
  for (const [name, email, expected] of [
    ['Claude Opus 4.6', 'noreply@anthropic.com', 'Claude'],
    ['Cursor', 'cursoragent@cursor.com', 'Cursor'],
    ['Codex', 'codex@openai.com', 'OpenAI Codex'],
    ['Copilot', '123+copilot@users.noreply.github.com', 'GitHub Copilot'],
  ]) {
    const trailer = `Co-authored-by: ${name} <${email}>`;
    const result = detectCommitAI(commit(`Implement feature\r\n\r\n${trailer}\r\n`));
    assert.equal(result.flagged, true);
    assert.deepEqual(result.tools, [expected]);
    assert.deepEqual(result.evidence, [{ source: 'coauthor', value: trailer, tool: expected }]);
  }
});

test('AI-agent authors and committers are distinguished from generic automation and human names', () => {
  const agent = { ...human, name: 'Copilot', login: 'copilot-swe-agent[bot]', email: '' };
  assert.equal(detectCommitAI(commit('Implement feature', { author: agent })).evidence[0].source, 'author');
  assert.equal(detectCommitAI(commit('Implement feature', { committer: agent })).evidence[0].source, 'committer');
  for (const identity of [
    { name: 'Claude', login: 'claude-person', email: 'claude@anthropic.com' },
    { name: 'GitHub', login: 'web-flow', email: 'noreply@github.com' },
    { name: 'dependabot[bot]', login: 'dependabot[bot]', email: 'dependabot@users.noreply.github.com' },
    { name: 'github-actions[bot]', login: 'github-actions[bot]', email: 'github-actions@users.noreply.github.com' },
  ]) assert.equal(detectCommitAI(commit('Update AI documentation', { author: identity, committer: identity })).flagged, false);
});

test('explicit AI declarations support custom tools without treating negative values as assistance', () => {
  const marked = detectCommitAI(commit('Implement feature\n\nAI-Assisted: YES\nAI-Tool: Private team assistant'));
  assert.equal(marked.flagged, true);
  assert.deepEqual(marked.tools, ['Private team assistant']);
  assert.equal(detectCommitAI(commit('Change\n\nAI-Generated: true')).flagged, true);
  assert.equal(detectCommitAI(commit('Change\n\nAI-Tool: Gemini CLI')).tools[0], 'Gemini');
  for (const value of ['false', 'NO', '0', 'none']) {
    assert.equal(detectCommitAI(commit(`Change\n\nAI-Assisted: ${value}\nAI-Tool: Claude Code`)).flagged, false);
    assert.equal(detectCommitAI(commit(`Change\n\nAI-Tool: ${value}`)).flagged, false);
  }
  assert.equal(detectCommitAI(commit('Change\n\nAI-Assisted: false\nCo-authored-by: Claude <noreply@anthropic.com>')).flagged, true);
});

test('generation footers are recognized while code, quotations and discussion of AI are not declarations', () => {
  for (const message of [
    'Change\n\n🤖 Generated with [Claude Code](https://claude.ai/code).',
    'Change\n\nGenerated by GitHub Copilot',
    'Change\n\nGenerated-By: Aider',
    'Change\n\nWritten using Codex CLI\n\nSigned-off-by: Alice <alice@example.test>',
  ]) assert.equal(detectCommitAI(commit(message)).flagged, true, message);
  for (const message of [
    'Fix the AI module and Claude documentation',
    'Generated with Claude Code is an example in the README',
    'Change\n\n> AI-Assisted: true',
    'Change\n\n```text\nAI-Assisted: true\n```',
    'Change\n\n```text\n\nAI-Assisted: true',
    'Change\n\n~~~text\n\nGenerated by Claude Code',
    'Explain examples\n\nGenerated by Claude Code\n\nThese are examples, not the provenance of this commit.',
  ]) assert.deepEqual(detectCommitAI(commit(message)), { flagged: false, tools: [], evidence: [] }, message);
});

test('analysis and commit-inspector metadata produce identical, deduplicated flags without mutations', () => {
  const message = 'Change\n\nCo-authored-by: Claude <noreply@anthropic.com>\nCo-authored-by: Claude <noreply@anthropic.com>\nAI-Tool: Claude Code';
  const metadata = Object.freeze(commit(message));
  const expected = detectCommitAI(metadata);
  assert.deepEqual(expected.tools, ['Claude']);
  assert.equal(expected.evidence.length, 2);
  assert.deepEqual(detectCommitAI({ message, author: human.name, authorIdentity: human, committerIdentity: human }), expected);
  assert.equal(metadata.message, message);
});

test('paginated history counts unique marked commits and includes flags discovered on later pages', () => {
  const marked = commit('Change\n\nAI-Assisted: true');
  const snapshot = { repository: { name: 'any-owner/any-repository' }, branch: 'feature', window: { since: null, until: '2026-01-04T00:00:00Z', days: 'all' }, commitsAvailable: true };
  const first = { ...snapshot, pages: [1], nextPage: 2, commits: [marked] };
  const second = { ...snapshot, pages: [2], commits: [marked, commit('Later\n\nAI-Tool: Cursor', { sha: 'b'.repeat(40) }), commit('Fix AI module', { sha: 'c'.repeat(40) })] };
  const merged = mergeGitHubAnalysis(first, second);
  assert.equal(merged.commits.length, 3);
  assert.equal(merged.commits.filter(item => detectCommitAI(item).flagged).length, 2);
  assert.equal(first.commits.length, 1);
});

test('CSV exports retain AI evidence, distinguish missing markers, and neutralize formula-shaped tool names', () => {
  const content = githubCommitCsv([commit('Change\n\nAI-Assisted: true\nAI-Tool: =HYPERLINK("https://example.test")'), commit('Fix AI module', { sha: 'b'.repeat(40) })]);
  assert.match(content, /"AI marker status","AI tools","AI evidence"/);
  assert.match(content, /"AI-assisted"/);
  assert.match(content, /"No marker found"/);
  assert.ok(content.includes('"\'=HYPERLINK(""https://example.test"")"'));
  assert.match(content, /trailer: AI-Assisted: true/);
});
