import { useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, ChevronRight, FileText, FolderKanban, GraduationCap, LayoutDashboard, Link2, Menu, ShieldCheck, Users, X } from 'lucide-react';
import '../home.css';

type AuthMode = 'signin' | 'signup';
type AuthRole = 'student' | 'faculty' | 'college' | 'recruiter';
interface HomePageProps { onOpenAuth: (mode: AuthMode, role?: AuthRole) => void }

const features = [
  { icon: LayoutDashboard, label: 'Overview', title: 'Know where to focus next', description: 'See real project progress, overdue deliveries, revision requests, review status, and profile readiness in one actionable overview.', points: ['Priority actions and project health', 'Live workspace totals', 'Search pages, projects, and milestones'] },
  { icon: FolderKanban, label: 'Projects and teams', title: 'Keep every project detail together', description: 'Create project workspaces, manage team roles and skills, assign a mentor, and keep your repository, designs, and boards close to the work.', points: ['Search, sort, archive, and restore projects', 'Editable members and project settings', 'Project-linked documents and research'] },
  { icon: CheckCircle2, label: 'Tasks and reviews', title: 'Turn delivery into visible progress', description: 'Plan dated milestones, attach submission links, submit for review, and keep feedback and scores with the right delivery.', points: ['List and status-board views', 'Overdue, review, and revision filters', 'Mentor review queue and evidence exports'] },
  { icon: CalendarDays, label: 'Calendar', title: 'Make space for every deadline', description: 'Explore deadlines by month or agenda, filter by project and completion, and select a day to see exactly what is due.', points: ['Today and month navigation', 'Project and delivery filters', 'Export selected dates to your calendar'] },
  { icon: BookOpen, label: 'Your academic library', title: 'Keep useful knowledge within reach', description: 'Build private research, resource, and document libraries with project links, tags, references, and your own notes.', points: ['Search titles, notes, and source URLs', 'Filter by project or exact tag', 'Edit entries and export saved records'] },
  { icon: Link2, label: 'Connected tools', title: 'Bring evidence back to the project', description: 'Inspect GitHub repositories, Figma designs, and Miro boards through the permissions granted by your connected account.', points: ['Public GitHub, authorization, or tokens', 'Repository files, commit history, and diffs', 'Design pages, versions, and board items'] },
  { icon: FileText, label: 'Blackbook and portfolio', title: 'Present the work you actually did', description: 'Combine project evidence with your authored report sections. Save a project-specific draft and return to it from another device.', points: ['Private saved drafts and editable reports', 'Markdown, printable HTML, and PDF printing', 'Academic profile and portfolio export'] },
  { icon: ShieldCheck, label: 'Account and sessions', title: 'Stay in control of your workspace', description: 'Use your personal account to access project records, private libraries, connected tools, and active-device details.', points: ['Required personal-password setup', 'Current-device and activity details', 'Sign out one device or other sessions'] },
];

const perspectives = [
  { label: 'For students', title: 'Know what to do next.', description: 'Keep project plans, deadlines, revision requests, research, reports, and your portfolio in the same workspace.', items: ['Plan milestones and submit evidence', 'Follow feedback and review scores', 'Build your academic record'], role: 'student' as const },
  { label: 'For project teams', title: 'Work from the same plan.', description: 'Share project details and milestone records while each person keeps their own private notes and references.', items: ['Manage members, roles, and skills', 'Keep connected tool links together', 'Track the same project deliveries'], role: 'student' as const },
  { label: 'For mentors', title: 'Review work with context.', description: 'Open assigned projects, inspect delivery evidence, approve submissions, and request revisions with useful feedback.', items: ['See submissions awaiting review', 'Review evidence inside the project', 'Record feedback and scores'], role: 'faculty' as const },
];

const faq = [
  ['How do I get started?', 'Create an account with your email address. Your initial six-digit login code is emailed to you. Sign in with that code, set your own personal password, and create your first project.'],
  ['How do team members and mentors access a project?', 'The project lead adds team members by email and assigns a mentor using their registered PlacePMS email. People sign in with their own accounts to access the projects assigned to them.'],
  ['What happens when I submit a milestone?', 'The milestone moves into review. Its assigned mentor can approve it or request revisions, with feedback and an optional score. Withdraw an unreviewed submission if you need to change its evidence.'],
  ['Do I need to connect every external tool?', 'No. Project planning, milestones, libraries, and reports work independently. Public GitHub inspection is available without a provider token. Private repositories, Figma files, and Miro boards require an authorized connection. OAuth options depend on the configured provider application.'],
  ['Can I upload documents directly?', 'Documents stores private written notes and links. Milestone evidence links to externally hosted documents. You can export your notes and reports, and print a generated Blackbook or save it as PDF using your browser.'],
  ['Does PlacePMS write my research or results for me?', 'The Blackbook builder combines your saved project records and references with the sections you write. It does not invent research, results, or claims. Save your draft to resume writing and edit the generated report before submitting it.'],
];

export default function HomePage({ onOpenAuth }: HomePageProps) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [preview, setPreview] = useState('overview');
  const [year] = useState(() => new Date().getFullYear());
  const openAuth = (mode: AuthMode, role: AuthRole = 'student') => { setMobileMenuOpen(false); onOpenAuth(mode, role); };
  const nav = <><a href="#features" onClick={() => setMobileMenuOpen(false)}>Features</a><a href="#how-it-works" onClick={() => setMobileMenuOpen(false)}>How it works</a><a href="#faq" onClick={() => setMobileMenuOpen(false)}>FAQ</a><a href="#get-started" onClick={() => setMobileMenuOpen(false)}>Get started</a></>;

  return <div className="home-page">
    <a className="home-skip" href="#home-main">Skip to content</a>
    <header className="home-header"><div className="home-container home-header-inner">
      <a href="/" aria-label="PlacePMS Home"><img src="/PlacePMS-Logo-Vector.svg" width="126" height="36" alt="PlacePMS" /></a>
      <nav className="home-desktop-nav" aria-label="Main navigation">{nav}</nav>
      <div className="home-desktop-actions"><button className="home-button home-button-plain" onClick={() => openAuth('signin')}>Sign In</button><button className="home-button home-button-primary" onClick={() => openAuth('signup')}>Create Account <ArrowRight size={15} /></button></div>
      <button className="home-menu-toggle" aria-label={mobileMenuOpen ? 'Close navigation menu' : 'Open navigation menu'} aria-expanded={mobileMenuOpen} aria-controls="home-mobile-navigation" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>{mobileMenuOpen ? <X size={23} /> : <Menu size={23} />}</button>
    </div>{mobileMenuOpen && <nav className="home-mobile-nav" id="home-mobile-navigation" aria-label="Mobile navigation">{nav}<button className="home-button" onClick={() => openAuth('signin')}>Sign In</button><button className="home-button home-button-primary" onClick={() => openAuth('signup')}>Create Account</button></nav>}</header>

    <main id="home-main">
      <section className="home-hero"><div className="home-container home-hero-grid"><div className="home-hero-copy"><span className="home-badge"><GraduationCap size={16} /> Academic project workspace</span><h1>Plan, build, and present your <span>academic work</span> in one place.</h1><p>From your first project idea to your final Blackbook, PlacePMS connects teams, mentors, milestones, research, and the tools behind your work.</p><div className="home-actions"><button className="home-button home-button-primary" onClick={() => openAuth('signup')}>Create Account <ArrowRight size={17} /></button><a className="home-button" href="#features">Explore the workspace <ChevronRight size={17} /></a></div><small>Start with a project. Build a clear plan. Keep your evidence connected.</small></div>
        <div className="home-preview"><div className="home-preview-heading"><div><span className="home-eyebrow">A look inside PlacePMS</span><h2>Your academic workspace</h2></div><FolderKanban size={23} /></div><div className="home-preview-tabs" aria-label="Workspace preview">{[['overview', 'Overview'], ['tasks', 'Milestones'], ['tools', 'Connected tools']].map(([value, label]) => <button key={value} aria-pressed={preview === value} onClick={() => setPreview(value)}>{label}</button>)}</div><div className="home-preview-body" aria-live="polite">
          {preview === 'overview' ? <><div className="home-preview-tiles"><div><FolderKanban size={18} /><span>Project health</span><strong>Clear priorities</strong></div><div><CheckCircle2 size={18} /><span>Next actions</span><strong>Visible progress</strong></div></div><article className="home-preview-card"><span className="home-eyebrow">Focus & next actions</span><h3>Know what needs your attention</h3><p>Overdue deliveries, review decisions, and project readiness come together in your overview.</p><a href="#features">Explore the overview <ArrowRight size={14} /></a></article></> : preview === 'tasks' ? <><div className="home-preview-flow">{['Plan', 'Submit', 'Review', 'Improve'].map((label, index) => <span key={label}><b>{String(index + 1).padStart(2, '0')}</b>{label}</span>)}</div><article className="home-preview-card"><span className="home-eyebrow">Milestone delivery</span><h3>A clear path from plan to approval</h3><p>Set dates, attach evidence, submit your work, and act on your mentor’s feedback.</p><a href="#how-it-works">See the workflow <ArrowRight size={14} /></a></article></> : <><div className="home-preview-tools">{['GitHub repositories', 'Figma designs', 'Miro boards'].map(label => <span key={label}><Link2 size={17} />{label}<ChevronRight size={14} /></span>)}</div><article className="home-preview-card"><h3>Inspect the evidence behind your work</h3><p>Connect your own accounts and browse the resources you have permission to access.</p><a href="#faq">How connections work <ArrowRight size={14} /></a></article></>}
          <div className="home-preview-footer"><span><CalendarDays size={15} /> Deadlines</span><span><BookOpen size={15} /> Research</span><span><FileText size={15} /> Reports</span></div><small className="home-preview-note">Product preview · Your dashboard uses your own saved records.</small>
        </div></div>
      </div></section>

      <section id="features" className="home-section home-section-white"><div className="home-container"><div className="home-section-heading"><span className="home-eyebrow">One connected workspace</span><h2>Everything you need to move a project forward.</h2><p>Every workspace section supports the same goal: a project that is planned, documented, reviewed, and ready to present.</p></div><div className="home-feature-grid">{features.map(({ icon: Icon, label, title, description, points }) => <article className="home-feature" key={label}><div className="home-feature-top"><span className="home-icon"><Icon size={22} /></span><span>{label}</span></div><h3>{title}</h3><p>{description}</p><ul>{points.map(point => <li key={point}><CheckCircle2 size={16} />{point}</li>)}</ul></article>)}</div></div></section>

      <section className="home-section"><div className="home-container"><div className="home-section-heading"><span className="home-eyebrow">Built around collaboration</span><h2>A clear place for every person involved.</h2><p>Shared project records support team coordination and mentor reviews. Your research notes and document library stay private to your account.</p></div><div className="home-perspective-grid">{perspectives.map((item, index) => <article className="home-perspective" key={item.label}><div className="home-feature-top"><span className="home-eyebrow">0{index + 1} / 03</span><Users size={21} /></div><span className="home-perspective-label">{item.label}</span><h3>{item.title}</h3><p>{item.description}</p><ul>{item.items.map(point => <li key={point}><ChevronRight size={16} />{point}</li>)}</ul><button className="home-text-button" onClick={() => openAuth('signin', item.role)}>{item.role === 'faculty' ? 'Mentor sign in' : 'Open your workspace'} <ArrowRight size={15} /></button></article>)}</div></div></section>

      <section className="home-connected"><div className="home-container home-connected-grid"><div><span className="home-eyebrow">From plan to presentation</span><h2>Let your project records tell the whole story.</h2><p>Your Blackbook combines actual project details, team members, milestone evidence, and saved research with the academic sections you write.</p><a className="home-button" href="#how-it-works">Build your academic record <ArrowRight size={16} /></a></div><div className="home-report-flow">{[['01', 'Plan the work', 'Project details, team, mentor, and dated milestones'], ['02', 'Keep the evidence', 'Submission links, feedback, scores, and references'], ['03', 'Write and present', 'Saved drafts, editable reports, and your portfolio']].map(([step, title, text]) => <article key={step}><span>{step}</span><div><h3>{title}</h3><p>{text}</p></div><CheckCircle2 size={20} /></article>)}</div></div></section>

      <section id="how-it-works" className="home-section home-section-white"><div className="home-container"><div className="home-section-heading"><span className="home-eyebrow">How it works</span><h2>A simple flow for academic project work.</h2><p>Start with the information you have. Add context and evidence as your project develops.</p></div><div className="home-process">{[['Create your profile', 'Sign in, set your personal password, and complete your academic details.'], ['Add a project', 'Name your project, add team members, assign a mentor, and link useful tools.'], ['Plan milestones', 'Describe each delivery, set due dates, and attach supporting documents.'], ['Review progress', 'Submit evidence, follow mentor feedback, and use your calendar to stay on track.'], ['Build your report', 'Write and save your Blackbook draft, generate a report, and export your portfolio.']].map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>

      <section id="faq" className="home-section"><div className="home-container home-faq-grid"><div className="home-section-heading"><span className="home-eyebrow">Useful answers</span><h2>Before your first project.</h2><p>Understand accounts, collaboration, connections, and reporting before you get started.</p></div><div className="home-faq">{faq.map(([question, answer]) => <details key={question}><summary>{question}<ChevronRight size={18} /></summary><p>{answer}</p></details>)}</div></div></section>

      <section id="get-started" className="home-section home-start"><div className="home-container"><span className="home-badge"><GraduationCap size={16} /> Start with your next project</span><h2>Bring your academic work together.</h2><p>Create your workspace and give your team, milestones, reviews, and academic records a clear place to grow.</p><div className="home-actions"><button className="home-button home-button-primary" onClick={() => openAuth('signup')}>Create Account <ArrowRight size={17} /></button><button className="home-button" onClick={() => openAuth('signin')}>Sign In to your workspace <ArrowRight size={17} /></button></div></div></section>
    </main>

    <footer className="home-footer"><div className="home-container"><div className="home-footer-grid"><div><a href="/" aria-label="PlacePMS Home"><img src="/PlacePMS-Logo-Vector.svg" width="126" height="36" alt="PlacePMS" /></a><p>A connected academic workspace for projects, milestones, reviews, research, documents, integrations, and reports.</p></div><div><h3>Workspace</h3><a href="#features">Explore every feature</a><a href="#how-it-works">How it works</a><a href="#faq">Frequently asked questions</a></div><div><h3>Your account</h3><button onClick={() => openAuth('signup')}>Create Account</button><button onClick={() => openAuth('signin')}>Student sign in</button><button onClick={() => openAuth('signin', 'faculty')}>Mentor sign in</button></div></div><div className="home-footer-bottom"><span>© {year} PlacePMS. Academic project work, connected.</span><span>Projects · Milestones · Research · Reports</span></div></div></footer>
  </div>;
}
