import { useState } from 'react';
import { BookOpen, CalendarDays, Check, Flag, Layers3, Users } from 'lucide-react';
import { planEndDate, type IdeaPlan } from '../lib/idea-plan';
import '../idea-plan.css';

const sections = [{ id: 'overview', label: 'Overview', icon: Flag }, { id: 'roadmap', label: 'Roadmap', icon: CalendarDays }, { id: 'team', label: 'Team roles', icon: Users }, { id: 'report', label: 'Blackbook', icon: BookOpen }] as const;

export default function IdeaPlanEditor({ plan, onChange, disabled = false }: { plan: IdeaPlan; onChange: (plan: IdeaPlan) => void; disabled?: boolean }) {
  const [section, setSection] = useState<(typeof sections)[number]['id']>('overview');
  const update = <K extends keyof IdeaPlan>(field: K, value: IdeaPlan[K]) => onChange({ ...plan, [field]: value });
  const end = planEndDate(plan);
  const renamePhase = (index: number, title: string) => {
    const old = plan.phases[index].title;
    onChange({ ...plan, phases: plan.phases.map((item, position) => position === index ? { ...item, title } : item), milestones: plan.milestones.map(item => item.phase === old ? { ...item, phase: title } : item) });
  };

  return <div className="idea-editor">
    <div className="idea-editor-summary"><span><Layers3 size={15} />{plan.weeks}-week roadmap</span><span><Flag size={15} />{plan.milestones.length} milestones</span><span><Users size={15} />{plan.teamSize} {plan.teamSize === 1 ? 'person' : 'people'}</span></div>
    <div className="idea-editor-tabs" aria-label="Explore your project plan">{sections.map(({ id, label, icon: Icon }) => <button type="button" key={id} aria-pressed={section === id} onClick={() => setSection(id)}><Icon size={14} />{label}</button>)}</div>
    <fieldset disabled={disabled} className="idea-editor-fields">
      {section === 'overview' && <div className="idea-overview">
       <label>Project title<input required maxLength={160} value={plan.title} onChange={event => update('title', event.target.value)} /></label>
       <label>Project summary<textarea required rows={3} maxLength={800} value={plan.summary} onChange={event => update('summary', event.target.value)} /></label>
        <div className="idea-editor-section-label"><strong>Project brief</strong><small>Confirm the context before you hand this plan to your workspace</small></div>
        <div className="idea-brief-grid"><label>Intended audience<input maxLength={240} placeholder="Who benefits from this project?" value={plan.audience} onChange={event => update('audience', event.target.value)} /></label><label>Definition of success<input maxLength={240} placeholder="What observable outcome would count as progress?" value={plan.successCriteria} onChange={event => update('successCriteria', event.target.value)} /></label></div>
        <label>Constraints or must-haves<input maxLength={400} placeholder="Important limits, dependencies, or requirements" value={plan.constraints} onChange={event => update('constraints', event.target.value)} /></label>
        <label>Project domain<input required maxLength={120} value={plan.domain} onChange={event => update('domain', event.target.value)} /></label>
        <div className="idea-editor-section-label"><strong>What you’re working towards</strong><small>Editable project objectives</small></div>
        <div className="idea-objectives">{plan.objectives.map((objective, index) => <label key={index}><span aria-hidden="true"><Check size={13} /></span><input aria-label={`Objective ${index + 1}`} required maxLength={160} value={objective} onChange={event => update('objectives', plan.objectives.map((item, position) => position === index ? event.target.value : item))} /></label>)}</div>
      </div>}
      {section === 'roadmap' && <div className="idea-roadmap">
        <div className="idea-editor-section-label"><strong>{plan.startDate} → {end}</strong><small>Adjust phases, deliverables, and dates</small></div>
        <div className="idea-phases">{plan.phases.map((phase, index) => <div className="idea-phase" key={phase.id}><span className="idea-phase-number">0{index + 1}</span><label>Phase {index + 1}<input required maxLength={80} value={phase.title} onChange={event => renamePhase(index, event.target.value)} /></label><div className="idea-date-grid"><label>Starts<input aria-label={`Phase ${index + 1} start date`} type="date" required min={plan.startDate} max={end} value={phase.startDate} onChange={event => update('phases', plan.phases.map((item, position) => position === index ? { ...item, startDate: event.target.value } : item))} /></label><label>Ends<input aria-label={`Phase ${index + 1} due date`} type="date" required min={phase.startDate || plan.startDate} max={end} value={phase.dueDate} onChange={event => update('phases', plan.phases.map((item, position) => position === index ? { ...item, dueDate: event.target.value } : item))} /></label></div></div>)}</div>
        <div className="idea-editor-section-label"><strong>Deliverables that move you forward</strong><small>These become real workspace milestones</small></div>
        <div className="idea-milestones">{plan.milestones.map((milestone, index) => <details className="idea-milestone" key={milestone.id}><summary><span>0{index + 1}</span><strong>{milestone.name || 'Untitled milestone'}</strong><time dateTime={milestone.dueDate}>{milestone.dueDate}</time></summary><div><label>Milestone {index + 1} name<input required maxLength={160} value={milestone.name} onChange={event => update('milestones', plan.milestones.map((item, position) => position === index ? { ...item, name: event.target.value } : item))} /></label><label>Description<textarea required rows={3} maxLength={800} value={milestone.description} onChange={event => update('milestones', plan.milestones.map((item, position) => position === index ? { ...item, description: event.target.value } : item))} /></label><label>Phase<select value={milestone.phase} onChange={event => update('milestones', plan.milestones.map((item, position) => position === index ? { ...item, phase: event.target.value } : item))}>{plan.phases.map(item => <option key={item.id} value={item.title}>{item.title || 'Untitled phase'}</option>)}</select></label><div className="idea-date-grid"><label>Start date<input aria-label={`Milestone ${index + 1} start date`} type="date" required min={plan.startDate} max={end} value={milestone.startDate} onChange={event => update('milestones', plan.milestones.map((item, position) => position === index ? { ...item, startDate: event.target.value } : item))} /></label><label>Due date<input aria-label={`Milestone ${index + 1} due date`} type="date" required min={milestone.startDate || plan.startDate} max={end} value={milestone.dueDate} onChange={event => update('milestones', plan.milestones.map((item, position) => position === index ? { ...item, dueDate: event.target.value } : item))} /></label></div></div></details>)}</div>
      </div>}
      {section === 'team' && <div className="idea-team-roles"><div className="idea-editor-section-label"><strong>A responsibility for every contributor</strong><small>Suggested roles; add real teammates after creating your project</small></div>{plan.roles.map((role, index) => <div className="idea-role" key={index}><span><Users size={17} /></span><div><label>Role {index + 1}<input required maxLength={60} value={role.title} onChange={event => update('roles', plan.roles.map((item, position) => position === index ? { ...item, title: event.target.value } : item))} /></label><label>Responsibility<textarea aria-label={`Role ${index + 1} responsibility`} required rows={2} maxLength={160} value={role.responsibility} onChange={event => update('roles', plan.roles.map((item, position) => position === index ? { ...item, responsibility: event.target.value } : item))} /></label></div></div>)}</div>}
      {section === 'report' && <div className="idea-report-outline"><div className="idea-editor-section-label"><strong>Your story, chapter by chapter</strong><small>Planning prompts for your own writing and project evidence</small></div>{plan.chapters.map((chapter, index) => <div className="idea-chapter" key={index}><span>0{index + 1}</span><div><label>Chapter {index + 1}<input required maxLength={100} value={chapter.title} onChange={event => update('chapters', plan.chapters.map((item, position) => position === index ? { ...item, title: event.target.value } : item))} /></label><label>Writing outline<textarea aria-label={`Chapter ${index + 1} outline`} required rows={3} maxLength={500} value={chapter.prompt} onChange={event => update('chapters', plan.chapters.map((item, position) => position === index ? { ...item, prompt: event.target.value } : item))} /></label></div></div>)}</div>}
    </fieldset>
  </div>;
}
