import { useMemo, useState } from 'react';
import { Activity, CalendarDays, Download, GitCommitHorizontal, GitMerge, ShieldCheck, Users } from 'lucide-react';
import type { GitHubAnalysis, GitHubWorkItem } from '../../lib/integration-types';
import { commitTime, formatGitHubDate, githubActivity, githubCommitCsv, githubContributors, githubCoverageComplete, utcDay } from '../../lib/github-analytics';
import { safeExternalUrl } from '../../lib/dashboard-data';
import { downloadText } from '../../lib/workspace-api';
import '../../github-analysis.css';

const number = (value: number) => value.toLocaleString();
const colors = ['#2d7f62', '#678bd8', '#d59b42', '#9673c7', '#ce7088', '#4eabb1', '#8794a6', '#ad885f'];
const weekdayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
function Link({ url, children }: { url: string; children: React.ReactNode }) {
  const safe = safeExternalUrl(url);
  return safe ? <a href={safe} target="_blank" rel="noreferrer" className="dash-text-link">{children}</a> : <span>{children}</span>;
}
function Chart({ title, values, labels, color = 'var(--dash-brand)' }: { title: string; values: number[]; labels: string[]; color?: string }) {
  const maximum = Math.max(1, ...values); const width = 720; const left = 45; const bottom = 175; const plotWidth = width - left - 15;
  const step = plotWidth / Math.max(1, values.length);
  return <svg className="github-chart" viewBox={`0 0 ${width} 215`} role="img" aria-label={title}>
    <title>{title}. {values.reduce((sum, value) => sum + value, 0)} total.</title>
    {[0, 0.5, 1].map(fraction => <g key={fraction}><line x1={left} x2={width - 15} y1={bottom - fraction * 145} y2={bottom - fraction * 145} className="github-chart-grid" /><text x={left - 8} y={bottom - fraction * 145 + 4} textAnchor="end">{number(Math.round(maximum * fraction))}</text></g>)}
    {values.map((value, index) => <rect key={`${labels[index]}-${index}`} x={left + index * step + Math.min(2, step / 8)} y={bottom - value / maximum * 145} width={Math.max(0.5, step - Math.min(4, step / 4))} height={value / maximum * 145} rx={Math.min(3, step / 4)} fill={color}><title>{labels[index]}: {number(value)}</title></rect>)}
    {[...new Set([0, Math.floor((values.length - 1) / 2), values.length - 1])].filter(index => index >= 0).map(index => <text key={index} x={left + index * step + step / 2} y={200} textAnchor={index === 0 ? 'start' : index === values.length - 1 ? 'end' : 'middle'}>{labels[index]}</text>)}
  </svg>;
}
function WorkItems({ title, items, limit }: { title: string; items: GitHubWorkItem[]; limit: number }) {
  return <article className="github-card"><h3>{title} <span className="github-badge">{items.length} loaded</span></h3><p className="workspace-muted">Repository-wide open items, up to {limit} returned by GitHub.</p>
    <div className="workspace-list">{items.map(item => <div key={item.number} className="workspace-list-item"><div><Link url={item.url}>#{item.number} {item.title}</Link><p>{item.author || 'Unknown account'}{item.draft ? ' · Draft' : ''} · Opened {formatGitHubDate(item.createdAt)}</p><small>Updated {formatGitHubDate(item.updatedAt)}{item.labels.length ? ` · ${item.labels.join(', ')}` : ''}</small></div></div>)}</div>
    {!items.length && <p className="workspace-muted">No items returned. Any provider access errors appear above this analysis.</p>}
  </article>;
}
interface Props {
  analysis: GitHubAnalysis;
  busy: string;
  progress: string;
  onCommit: (sha: string) => void;
  onLoadMore: (all: boolean) => void;
  onAnalyzeChanges: () => void;
  onStop: () => void;
}
export default function GitHubRepositoryAnalysis({ analysis, busy, progress, onCommit, onLoadMore, onAnalyzeChanges, onStop }: Props) {
  const [tab, setTab] = useState('Activity'); const [author, setAuthor] = useState(''); const [search, setSearch] = useState('');
  const [commitDay, setCommitDay] = useState(''); const [kind, setKind] = useState('all'); const [page, setPage] = useState(1);
  const contributors = useMemo(() => githubContributors(analysis.commits), [analysis.commits]);
  const activity = useMemo(() => githubActivity(analysis, author), [analysis, author]);
  const filtered = useMemo(() => activity.commits.filter(commit => (!commitDay || utcDay(commitTime(commit)) === commitDay)
    && (kind === 'all' || (kind === 'merge' ? commit.parents.length > 1 : kind === 'verified' ? commit.verified : commit.parents.length <= 1))
    && (!search.trim() || `${commit.message} ${commit.sha} ${commit.author.name} ${commit.author.login} ${commit.author.email} ${commit.committer.name} ${commit.committer.login}`.toLowerCase().includes(search.trim().toLowerCase())))
    .sort((a, b) => commitTime(b).localeCompare(commitTime(a))), [activity.commits, commitDay, kind, search]);
  const pages = Math.max(1, Math.ceil(filtered.length / 25)); const currentPage = Math.min(page, pages);
  const visible = filtered.slice((currentPage - 1) * 25, currentPage * 25);
  const maxDay = Math.max(1, ...activity.heatmap.map(point => point.commits));
  const totalLanguageBytes = analysis.languages.reduce((sum, language) => sum + language.bytes, 0);
  const languageGradient = analysis.languages.reduce<{ stops: string[]; position: number }>((current, language, index) => {
    const position = current.position + language.bytes / Math.max(1, totalLanguageBytes) * 100;
    return { position, stops: [...current.stops, `${colors[index % colors.length]} ${current.position}% ${position}%`] };
  }, { stops: [], position: 0 }).stops.join(', ');
  const complete = githubCoverageComplete(analysis);
  const measuredTotal = analysis.commits.filter(commit => commit.stats).length;
  const chooseAuthor = (key: string) => { setAuthor(key); setPage(1); };
  const topContributor = contributors[0];
  return <div className="github-analysis">
    <div className="github-analysis-heading"><div><span className="github-eyebrow">REPOSITORY INTELLIGENCE</span><h3>Who contributed, what changed, and when</h3><p>{analysis.branch} · {analysis.window.days === 'all' ? 'All history' : `${analysis.window.days} days`} · Snapshot {formatGitHubDate(analysis.window.until)}</p></div><span className="github-badge">{analysis.repository.visibility}{analysis.repository.archived ? ' · Archived' : ''}</span></div>
    <div className="github-coverage" role="status"><strong>{number(analysis.commits.length)} unique commits loaded</strong><span>{complete ? 'Complete selected history' : 'Partial history'} · {analysis.pages.length} API page{analysis.pages.length === 1 ? '' : 's'} · Change statistics for {measuredTotal}/{analysis.commits.length} commits</span></div>
    <div className="workspace-actions github-load-controls">
      {analysis.nextPage && <><button className="dash-button" disabled={!!busy} onClick={() => onLoadMore(false)}>Load next 100 commits</button><button className="dash-button" disabled={!!busy} onClick={() => onLoadMore(true)}>Load more history (up to 1,000)</button></>}
      <button className="dash-button" disabled={!!busy || measuredTotal === analysis.commits.length} onClick={onAnalyzeChanges}>{busy === 'stats' ? 'Analyzing changes…' : 'Analyze changes for loaded commits'}</button>
      {(busy === 'stats' || busy === 'history') && <button className="dash-button" onClick={onStop}>Stop analysis</button>}
      {progress && <span className="github-progress" role="status">{progress}</span>}
    </div>
    <p className="workspace-muted">Charts use the commit's committer timestamp in UTC. Author and committer are shown separately below. Contributor counts are authored commits in the loaded history, including merges; co-author trailers are not counted as separate commits. Change analysis reads each loaded commit through your selected GitHub access.</p>
    <div className="github-filters"><label>Contributor filter<select className="workspace-input" value={author} onChange={event => chooseAuthor(event.target.value)}><option value="">All contributors</option>{contributors.map(item => <option key={item.identity.key} value={item.identity.key}>{item.identity.login || item.identity.name} ({item.commits})</option>)}</select></label><button className="dash-button" onClick={() => downloadText('github-commits.csv', githubCommitCsv(filtered), 'text/csv;charset=utf-8')}><Download size={14} />Export filtered commits</button></div>
    <div className="github-summary">
      {[{ icon: GitCommitHorizontal, label: 'Loaded commits', value: activity.commits.length }, { icon: Users, label: 'Contributors', value: author ? Number(activity.commits.length > 0) : contributors.length }, { icon: CalendarDays, label: 'Active UTC days', value: activity.activeDays }, { icon: GitMerge, label: 'Merge commits', value: activity.merges }, { icon: ShieldCheck, label: 'Verified signatures', value: activity.verified }].map(item => <div key={item.label}><item.icon size={17} /><span>{item.label}</span><strong>{number(item.value)}</strong></div>)}
    </div>
    <div className="github-navigation" aria-label="Repository analysis sections">{['Activity', 'Contributors', 'Commits', 'Repository'].map(value => <button className="dash-button" key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{value}</button>)}</div>
    {tab === 'Activity' && <div className="github-grid">
      <article className="github-card github-wide"><div className="github-card-heading"><div><h3><Activity size={17} />Commit activity</h3><p>{activity.interval === 'day' ? 'Daily' : activity.interval === 'week' ? 'Weekly (Monday start)' : 'Monthly'} commits · UTC · {activity.firstCommit || 'No commits'}{activity.lastCommit ? ` → ${activity.lastCommit}` : ''}</p></div></div>
        {activity.commits.length ? <Chart title="Commit activity graph" values={activity.timeline.map(point => point.commits)} labels={activity.timeline.map(point => point.date)} /> : <div className="github-empty">No commits loaded for this selection. Try another branch/window or load more history.</div>}
        <details className="github-chart-data"><summary>View activity data</summary><div className="github-table-scroll"><table className="github-table"><thead><tr><th>Period start (UTC)</th><th>Commits</th><th>Measured commits</th><th>Additions</th><th>Deletions</th></tr></thead><tbody>{activity.timeline.map(point => <tr key={point.date}><td>{point.date}</td><td>{point.commits}</td><td>{point.measuredCommits}</td><td>{point.measuredCommits ? `+${point.additions}` : '—'}</td><td>{point.measuredCommits ? `−${point.deletions}` : '—'}</td></tr>)}</tbody></table></div></details>
        {activity.missingDates > 0 && <p className="workspace-muted">{activity.missingDates} commits have no valid timestamp and are excluded from time charts.</p>}
      </article>
      <article className="github-card github-wide"><h3>Contribution heatmap</h3><p className="workspace-muted">Up to the latest 365 calendar days in the loaded window. Select an active day to see its commits.</p>
        <div className="github-heatmap-scroll"><div className="github-heatmap" style={{ gridTemplateColumns: `repeat(${Math.ceil(activity.heatmap.length / 7)}, 12px)` }}>{activity.heatmap.map(point => <button key={point.date} className={`github-heat-cell github-intensity-${point.commits ? Math.max(1, Math.ceil(point.commits / maxDay * 4)) : 0}`} disabled={!point.commits} title={`${point.date}: ${point.commits} commits (UTC)`} aria-label={`${point.date}, ${point.commits} commits`} onClick={() => { setCommitDay(point.date); setTab('Commits'); setPage(1); }} />)}</div></div>
        <div className="github-heatmap-legend"><span>{activity.heatmap[0]?.date}</span><span>Less {[0, 1, 2, 3, 4].map(level => <i key={level} className={`github-heat-cell github-intensity-${level}`} />)} More</span><span>{activity.heatmap.at(-1)?.date}</span></div>
      </article>
      <article className="github-card"><h3>Contributor distribution</h3><p className="workspace-muted">Top 10 by authored commits in all loaded history. Select a contributor to filter charts.</p>
        {contributors.slice(0, 10).map(item => <button key={item.identity.key} className="github-contributor-bar" aria-pressed={author === item.identity.key} onClick={() => chooseAuthor(author === item.identity.key ? '' : item.identity.key)}><span>{item.identity.login || item.identity.name}</span><strong>{item.commits} <small>({(item.commits / Math.max(1, analysis.commits.length) * 100).toFixed(1)}%)</small></strong><i><b style={{ width: `${item.commits / Math.max(1, topContributor?.commits || 0) * 100}%` }} /></i></button>)}
        {!contributors.length && <p className="workspace-muted">Contributor data appears after commits are loaded.</p>}
      </article>
      <article className="github-card"><h3>Language composition</h3><p className="workspace-muted">Repository-wide bytes reported by GitHub for the default branch, independent of the contributor filter.</p>
        {totalLanguageBytes > 0 ? <div className="github-language-layout"><div className="github-donut" role="img" aria-label={`Language distribution: ${analysis.languages.map(language => `${language.name} ${(language.bytes / totalLanguageBytes * 100).toFixed(1)}%`).join(', ')}`} style={{ background: `conic-gradient(${languageGradient})` }}><div><strong>{analysis.languages.length}</strong><span>languages</span></div></div><ul className="github-language-legend">{analysis.languages.map((language, index) => <li key={language.name}><i style={{ background: colors[index % colors.length] }} /><span>{language.name}<small>{number(language.bytes)} bytes</small></span><strong>{(language.bytes / totalLanguageBytes * 100).toFixed(1)}%</strong></li>)}</ul></div> : <div className="github-empty">No language data returned by GitHub.</div>}
      </article>
      <article className="github-card"><h3>Day-of-week activity</h3><Chart title="Commits by day of week in UTC" values={activity.weekdays} labels={weekdayNames} /><p className="workspace-muted">{weekdayNames[activity.weekdays.indexOf(Math.max(...activity.weekdays))]} has the most loaded commits{activity.commits.length ? ` (${Math.max(...activity.weekdays)})` : ': no activity yet'}.</p></article>
      <article className="github-card"><h3>Time-of-day activity</h3><Chart title="Commits by hour in UTC" values={activity.hours} labels={activity.hours.map((_, hour) => `${String(hour).padStart(2, '0')}:00`)} /><p className="workspace-muted">Hours are UTC, rather than the contributor's local timezone.</p></article>
      <article className="github-card github-wide"><h3>Code change activity</h3><p className="workspace-muted">Additions and deletions for {activity.measuredCommits} of {activity.commits.length} selected commits. Unmeasured changes are unknown; load change statistics to expand this graph.</p>
        <div className="github-churn-totals"><span className="workspace-added">{activity.measuredCommits ? `+${number(activity.additions)}` : '—'} additions</span><span className="workspace-removed">{activity.measuredCommits ? `−${number(activity.deletions)}` : '—'} deletions</span><span>{activity.measuredCommits ? number(activity.additions - activity.deletions) : '—'} net lines</span></div>
        {activity.measuredCommits ? <div className="github-churn-grid"><div><h4>Additions</h4><Chart title="Code additions graph for measured commits" values={activity.timeline.map(point => point.additions)} labels={activity.timeline.map(point => point.date)} /></div><div><h4>Deletions</h4><Chart title="Code deletions graph for measured commits" values={activity.timeline.map(point => point.deletions)} labels={activity.timeline.map(point => point.date)} color="#c34b42" /></div></div> : <div className="github-empty">Use “Analyze changes for loaded commits” to read real per-commit additions and deletions.</div>}
        {!!activity.changedFiles.length && <><h4>Most frequently changed files</h4><p className="workspace-muted">File counts describe measured commits{activity.filesTruncated ? '; some commits return only the first 100 files' : ''}. A renamed path is counted under its new name.</p><div className="github-table-scroll"><table className="github-table"><thead><tr><th>Path</th><th>Commits touching file</th><th>Additions</th><th>Deletions</th></tr></thead><tbody>{activity.changedFiles.slice(0, 20).map(file => <tr key={file.name}><td><code>{file.name}</code></td><td>{file.commits}</td><td className="workspace-added">+{file.additions}</td><td className="workspace-removed">−{file.deletions}</td></tr>)}</tbody></table></div></>}
      </article>
    </div>}
    {tab === 'Contributors' && <article className="github-card"><h3>Contributor breakdown</h3><p className="workspace-muted">GitHub accounts are grouped by login; unlinked Git identities by email, then name. First/last dates and active days use commit timestamps within the loaded history. Change totals cover only measured commits.</p><div className="github-table-scroll"><table className="github-table"><thead><tr><th>Contributor</th><th>Commits / share</th><th>Active days</th><th>First commit (UTC)</th><th>Latest commit (UTC)</th><th>Changes measured</th></tr></thead><tbody>{contributors.map(item => <tr key={item.identity.key} className={author === item.identity.key ? 'github-selected-row' : ''}><td><button className="workspace-title-button" onClick={() => { chooseAuthor(item.identity.key); setTab('Commits'); }}>{item.identity.name}</button><small>{item.identity.login ? `@${item.identity.login}` : item.identity.email || 'Unlinked Git identity'}</small>{item.identity.url && <Link url={item.identity.url}>GitHub profile</Link>}</td><td><strong>{item.commits}</strong><small>{(item.commits / Math.max(1, analysis.commits.length) * 100).toFixed(1)}% · {item.merges} merges · {item.verified} verified</small></td><td>{item.activeDays}</td><td>{formatGitHubDate(item.firstCommit)}</td><td>{formatGitHubDate(item.lastCommit)}</td><td>{item.measuredCommits}/{item.commits}<small>{item.measuredCommits ? `+${number(item.additions)} / −${number(item.deletions)}` : 'Not analyzed'}</small></td></tr>)}</tbody></table></div>{!contributors.length && <div className="github-empty">No contributors loaded.</div>}</article>}
    {tab === 'Commits' && <article className="github-card"><div className="github-card-heading"><div><h3>Detailed commit timeline</h3><p>Who authored and committed each change, with exact UTC timestamps and full messages.</p></div><span className="github-badge">{filtered.length} matching</span></div>
      <div className="github-commit-filters"><label>Search commits<input className="workspace-input" value={search} placeholder="Message, SHA, name, username or email" onChange={event => { setSearch(event.target.value); setPage(1); }} /></label><label>Commit type<select className="workspace-input" value={kind} onChange={event => { setKind(event.target.value); setPage(1); }}><option value="all">All commits</option><option value="regular">Non-merge commits</option><option value="merge">Merge commits</option><option value="verified">Verified signatures</option></select></label><label>Commit day (UTC)<input className="workspace-input" type="date" value={commitDay} onChange={event => { setCommitDay(event.target.value); setPage(1); }} /></label><button className="dash-button" onClick={() => { chooseAuthor(''); setSearch(''); setKind('all'); setCommitDay(''); setPage(1); }}>Clear commit filters</button></div>
      <div className="github-timeline">{visible.map(commit => <article key={commit.sha} className="github-commit"><div className="github-commit-dot">{commit.parents.length > 1 ? <GitMerge size={16} /> : <GitCommitHorizontal size={16} />}</div><div className="github-commit-body"><div className="github-commit-title"><button className="workspace-title-button" disabled={!!busy} onClick={() => onCommit(commit.sha)}>{commit.message.split('\n')[0] || 'Untitled commit'}</button><code>{commit.sha.slice(0, 7)}</code></div><div className="github-commit-people"><p><strong>Author:</strong> {commit.author.name}{commit.author.login ? ` (@${commit.author.login})` : ''}<small>Authored {formatGitHubDate(commit.authoredAt)}{commit.author.email ? ` · ${commit.author.email}` : ''}</small></p><p><strong>Committer:</strong> {commit.committer.name}{commit.committer.login ? ` (@${commit.committer.login})` : ''}<small>Committed {formatGitHubDate(commit.committedAt)}</small></p></div><div className="workspace-actions"><span className="github-badge">{commit.parents.length > 1 ? `Merge · ${commit.parents.length} parents` : 'Commit'}</span><span className="github-badge">{commit.verified ? 'Verified signature' : 'Signature not verified'}{commit.verificationReason ? ` · ${commit.verificationReason}` : ''}</span>{commit.stats ? <><span className="workspace-added">+{commit.stats.additions}</span><span className="workspace-removed">−{commit.stats.deletions}</span></> : <small className="github-unknown">Changes not yet analyzed</small>}<Link url={commit.url}>Open on GitHub</Link></div>{commit.message.includes('\n') && <details className="github-message"><summary>Full commit message</summary><pre>{commit.message}</pre></details>}<button className="dash-button github-diff-button" disabled={!!busy} onClick={() => onCommit(commit.sha)}>Inspect files &amp; diff</button></div></article>)}</div>
      {!filtered.length && <div className="github-empty">No loaded commits match these filters.</div>}
      <div className="github-pagination"><button className="dash-button" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Previous</button><span>Page {currentPage} of {pages} · 25 commits per page</span><button className="dash-button" disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}>Next</button></div>
    </article>}
    {tab === 'Repository' && <div className="github-grid"><article className="github-card"><h3>Repository facts</h3><dl className="github-facts">{Object.entries({ Repository: analysis.repository.name, 'Default branch': analysis.repository.defaultBranch, Visibility: analysis.repository.visibility, Created: formatGitHubDate(analysis.repository.createdAt), 'Latest push': formatGitHubDate(analysis.repository.pushedAt), License: analysis.repository.license || 'Not specified', 'GitHub repository size': `${number(analysis.repository.sizeKb)} KB`, Stars: number(analysis.repository.stars), Forks: number(analysis.repository.forks), 'Open issues + pull requests': number(analysis.repository.openIssuesAndPulls) }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{!!analysis.repository.topics.length && <div className="workspace-actions">{analysis.repository.topics.map(topic => <span className="github-badge" key={topic}>{topic}</span>)}</div>}</article>
      <article className="github-card"><h3>Branches</h3><p className="workspace-muted">Up to 100 repository branches; this report analyzes {analysis.branch} only.</p><div className="workspace-list">{analysis.branches.map(branch => <div className="workspace-list-item" key={branch.name}><div><Link url={`https://github.com/${analysis.repository.name}/tree/${encodeURIComponent(branch.name)}`}>{branch.name}</Link><small>{branch.sha.slice(0, 7)}{branch.protected ? ' · Protected' : ''}{branch.name === analysis.repository.defaultBranch ? ' · Default' : ''}</small></div></div>)}</div></article>
      <WorkItems title="Open pull requests" items={analysis.pulls} limit={30} /><WorkItems title="Open issues" items={analysis.issues} limit={50} />
      <article className="github-card github-wide"><h3>Repository contributor totals</h3><p className="workspace-muted">Up to 30 contributors reported by GitHub for default-branch history. These totals have a different scope from the selected-branch/window graphs.</p><div className="github-repository-contributors">{analysis.contributors.map(item => <div key={item.login}><Link url={item.url}>{item.login}</Link><strong>{number(item.commits)} commits</strong></div>)}</div>{!analysis.contributors.length && <p className="workspace-muted">No contributor totals returned.</p>}</article>
    </div>}
  </div>;
}
