import { useMemo, useState, type ReactNode } from 'react';
import { Activity, ArrowUpRight, CheckCircle2, Circle, FileCode2, GitBranch, Package, Rocket, Workflow } from 'lucide-react';
import type { GitHubAnalysis, GitHubIntelligenceSource, GitHubRepositoryIntelligence } from '../../lib/integration-types';
import { formatGitHubDate } from '../../lib/github-analytics';
import { githubAutomationSignals, githubDeliverySignals, isWorkflowFailure } from '../../lib/github-intelligence';
import { safeExternalUrl } from '../../lib/dashboard-data';
import { DetailDialog, RecordPager, WorkspaceSections } from './WorkspaceUI';

function External({ url, children }: { url: string; children: ReactNode }) { const safe = safeExternalUrl(url); return safe ? <a className="dash-text-link" href={safe} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={12} /></a> : <span>{children}</span>; }
function Metric({ label, value, note }: { label: string; value: ReactNode; note: string }) { return <div className="intel-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function Unavailable({ source }: { source: string }) { return <div className="studio-empty"><Workflow size={26} /><h3>{source} unavailable</h3><p>This provider data was not returned. Check the provider notices and your repository access, then start a fresh inspection.</p></div>; }

export default function GitHubIntelligencePanel({ analysis, author, onChanges }: { analysis: GitHubAnalysis; author: string; onChanges: () => void }) {
  const [tab, setTab] = useState('delivery'); const [automationTab, setAutomationTab] = useState('runs');
  const [runPage, setRunPage] = useState(1); const [workflowPage, setWorkflowPage] = useState(1); const [releasePage, setReleasePage] = useState(1);
  const [runFilter, setRunFilter] = useState('all'); const [runSearch, setRunSearch] = useState('');
  const [release, setRelease] = useState<GitHubRepositoryIntelligence['releases'][number] | null>(null);
  const signals = useMemo(() => githubDeliverySignals(analysis, author), [analysis, author]); const automation = githubAutomationSignals(analysis.intelligence);
  const intelligence = analysis.intelligence; const available = (source: GitHubIntelligenceSource) => intelligence?.coverage[source].available;
  const runs = intelligence?.runs.filter(run => (runFilter === 'all' || (runFilter === 'branch' ? run.branch === analysis.branch : runFilter === 'failure' ? isWorkflowFailure(run.conclusion) : run.conclusion === runFilter)) && `${run.name} ${run.branch} ${run.event} ${run.sha}`.toLowerCase().includes(runSearch.trim().toLowerCase())) || [];
  const currentRun = Math.min(runPage, Math.max(1, Math.ceil(runs.length / 5))); const currentWorkflow = Math.min(workflowPage, Math.max(1, Math.ceil((intelligence?.workflows.length || 0) / 6))); const currentRelease = Math.min(releasePage, Math.max(1, Math.ceil((intelligence?.releases.length || 0) / 4)));
  const coverage = (source: GitHubIntelligenceSource, limit: number) => <p className="intel-scope">Repository-wide provider sample · up to {limit} returned{intelligence?.coverage[source].hasMore ? ' · more records exist on GitHub' : ''} · independent of commit-window and contributor filters.</p>;
  const delivery = <div className="intel-delivery">
    <div className="intel-heading"><div><span className="dash-eyebrow">DELIVERY SIGNALS</span><h3>Understand the work behind the commits.</h3></div><span className="github-badge">{signals.complete ? 'Complete selected history' : 'Loaded history only'}</span></div>
    {!signals.available ? <Unavailable source="Commit signals" /> : <>
      <div className="intel-metrics">
        <Metric label="Longest active-day streak" value={`${signals.longestStreak}d`} note="Consecutive UTC days with loaded commits" />
        <Metric label="Observed commit cadence" value={signals.commitsPerCalendarDay === null ? '—' : `${signals.commitsPerCalendarDay.toFixed(2)}/d`} note="Dated loaded commits / calendar days in scope" />
        <Metric label="Median commit interval" value={signals.medianGapHours === null ? '—' : `${signals.medianGapHours.toFixed(1)}h`} note="Observed gaps; at least two dated commits" />
        <Metric label="Top contributor share" value={signals.topContributor ? `${signals.topShare.toFixed(1)}%` : '—'} note={signals.topContributor?.identity.login || signals.topContributor?.identity.name || 'No contributors returned'} />
        <Metric label="Measured change coverage" value={`${signals.measured}/${signals.loaded}`} note="Unmeasured additions and deletions stay unknown" />
        <Metric label="AI-marked commits" value={`${signals.aiMarked}/${signals.loaded}`} note={signals.aiTools.join(', ') || 'Explicit provenance markers only'} />
      </div>
      <article className="intel-panel"><div className="intel-heading"><h3><Activity size={16} />Dated activity comparison</h3><span className="github-badge">UTC</span></div><div className="intel-comparison"><div><strong>{signals.recentWeek}</strong><span>Latest 7 days, loaded</span></div><div><strong>{signals.trendCovered ? signals.precedingWeek : '—'}</strong><span>Preceding 7 days</span></div><div><strong>{signals.trendPercent !== null ? `${signals.trendPercent > 0 ? '+' : ''}${signals.trendPercent}%` : signals.trendCovered ? signals.recentWeek ? 'New activity' : 'Quiet period' : 'Partial scope'}</strong><span>{signals.trendCovered ? 'Complete 14-day comparison' : 'Complete 14-day history required'}</span></div></div><p className="intel-scope">{signals.loaded} loaded commits · {signals.activeDays} active UTC days · {signals.merges} merges · {signals.verified} verified signatures{signals.missingDates ? ` · ${signals.missingDates} undated commits excluded from timing` : ''}.</p></article>
      <details className="studio-section-note"><summary>Measured file hotspots ({signals.changedFiles.length})</summary>{signals.changedFiles.length ? <div className="intel-hotspots">{signals.changedFiles.slice(0, 6).map(file => <div key={file.name}><code>{file.name}</code><span>{file.commits} commits · +{file.additions} / −{file.deletions}</span><i style={{ width: `${file.commits / Math.max(1, signals.measured) * 100}%` }} /></div>)}<p className="intel-scope">Top six observed paths{signals.filesTruncated ? ' · some commits have truncated file lists' : ''}. Explore all loaded paths in Code changes.</p><button className="dash-button" onClick={onChanges}>Explore code changes<ArrowUpRight size={13} /></button></div> : <p>Analyze changes for loaded commits to populate actual file evidence.</p>}</details>
    </>}
  </div>;
  const runView = available('runs') ? <>
    <div className="intel-metrics intel-metrics-four"><Metric label="Successful runs" value={automation.successful} note="Returned completed runs with success conclusion" /><Metric label="Failed runs" value={automation.failed} note="Failure, timeout, startup, or action-required conclusions" /><Metric label="Active runs" value={automation.active} note="Queued, waiting, requested, or in progress" /><Metric label="Median observed duration" value={automation.medianObservedMinutes === null ? '—' : `${automation.medianObservedMinutes.toFixed(1)}m`} note="Completed run start → last update" /></div>
    <div className="workspace-actions intel-filters"><input className="workspace-input" aria-label="Search workflow runs" placeholder="Workflow, branch, event or SHA…" value={runSearch} onChange={event => { setRunSearch(event.target.value); setRunPage(1); }} /><select className="workspace-input" aria-label="Filter workflow runs" value={runFilter} onChange={event => { setRunFilter(event.target.value); setRunPage(1); }}><option value="all">All returned runs</option><option value="branch">Analyzed branch: {analysis.branch}</option><option value="success">Successful</option><option value="failure">Failed</option><option value="cancelled">Cancelled</option></select></div>
    <div className="intel-records">{runs.slice((currentRun - 1) * 5, currentRun * 5).map(run => <article key={run.id}><span className={`intel-state ${run.conclusion === 'success' ? 'is-success' : isWorkflowFailure(run.conclusion) ? 'is-failure' : ''}`}><Workflow size={16} /></span><div><External url={run.url}>{run.name || 'Workflow run'}</External><p><GitBranch size={11} />{run.branch || 'Branch not provided'} · {run.event || 'Event not provided'} · {run.sha.slice(0, 7)}</p><small>Started {formatGitHubDate(run.startedAt)}</small></div><span className="github-badge">{(run.conclusion || run.status || 'Unknown state').replace(/_/g, ' ')}</span></article>)}</div>{!runs.length && <div className="studio-empty"><Workflow size={25} /><h3>No matching returned runs</h3><p>Try another filter or open GitHub for additional history.</p></div>}<RecordPager page={currentRun} total={runs.length} size={5} onChange={setRunPage} noun="workflow runs" />{coverage('runs', 20)}
  </> : <Unavailable source="Workflow runs" />;
  const workflowView = available('workflows') ? <><div className="studio-card-grid">{intelligence!.workflows.slice((currentWorkflow - 1) * 6, currentWorkflow * 6).map(workflow => <article className="studio-card" key={workflow.id}><div className="studio-card-top"><span className="studio-card-icon"><FileCode2 size={20} /></span><span className="github-badge">{workflow.state.replace(/_/g, ' ') || 'Unknown state'}</span></div><h3><External url={workflow.url}>{workflow.name || 'Workflow'}</External></h3><p className="workspace-notes"><code>{workflow.path}</code></p><small className="studio-card-meta">Updated {formatGitHubDate(workflow.updatedAt)}</small></article>)}</div>{!intelligence!.workflows.length && <div className="studio-empty"><h3>No workflows returned</h3><p>This repository does not return any workflows in the current API sample.</p></div>}<RecordPager page={currentWorkflow} total={intelligence!.workflows.length} size={6} onChange={setWorkflowPage} noun="workflows" />{coverage('workflows', 30)}</> : <Unavailable source="CI workflows" />;
  const releases = available('releases') ? <><div className="studio-card-grid">{intelligence!.releases.slice((currentRelease - 1) * 4, currentRelease * 4).map(item => <article className="studio-card" key={item.id}><div className="studio-card-top"><span className="studio-card-icon"><Package size={22} /></span><span className="github-badge">{item.draft ? 'Draft' : item.prerelease ? 'Prerelease' : 'Release'}</span></div><h3>{item.title || item.tag}</h3><p>{item.tag} · {item.assets} assets</p><small className="studio-card-meta">{item.author || 'Author not provided'} · {formatGitHubDate(item.publishedAt)}</small><div className="studio-card-actions"><button className="dash-button" onClick={() => setRelease(item)}>Inspect release notes</button><External url={item.url}>Open release</External></div></article>)}</div>{!intelligence!.releases.length && <div className="studio-empty"><Rocket size={26} /><h3>No releases returned</h3><p>Published releases appear here when they are accessible to your connection.</p></div>}<RecordPager page={currentRelease} total={intelligence!.releases.length} size={4} onChange={setReleasePage} noun="releases" />{coverage('releases', 10)}</> : <Unavailable source="Release history" />;
  const standards = available('standards') ? <article className="intel-panel"><div className="intel-heading"><div><h3>Repository conventions</h3><p className="intel-scope">Files reported by GitHub’s repository community profile.</p></div>{intelligence?.communityHealth !== undefined && <span className="github-badge">GitHub profile: {intelligence.communityHealth}%</span>}</div><div className="intel-conventions">{intelligence!.standards.map(item => <div key={item.name}>{item.present ? <CheckCircle2 size={17} /> : <Circle size={17} />}<strong>{item.name}</strong><span>{item.present ? 'Reported present' : 'Not reported'}</span>{item.url && <External url={item.url}>View file</External>}</div>)}</div><p className="intel-scope">File presence and the profile percentage are reported directly by GitHub.</p></article> : <Unavailable source="Repository conventions" />;
  return <div className="github-intelligence"><WorkspaceSections label="Repository intelligence views" value={tab} onChange={setTab} sections={[{ id: 'delivery', label: 'Delivery signals', content: delivery }, { id: 'automation', label: 'CI & workflows', content: <WorkspaceSections label="Automation views" value={automationTab} onChange={setAutomationTab} sections={[{ id: 'runs', label: 'Recent runs', count: intelligence?.runs.length, content: runView }, { id: 'workflows', label: 'Workflows', count: intelligence?.workflows.length, content: workflowView }]} /> }, { id: 'releases', label: 'Releases', count: intelligence?.releases.length, content: releases }, { id: 'standards', label: 'Conventions', content: standards }]} />{intelligence && <p className="intel-scope">Repository metadata captured {formatGitHubDate(intelligence.capturedAt)}. Refresh the inspection for a newer snapshot.</p>}{release && <DetailDialog title={release.title || release.tag} subtitle={`${release.tag} · ${formatGitHubDate(release.publishedAt)}`} wide onClose={() => setRelease(null)}><div className="workspace-actions"><span className="github-badge">{release.assets} assets returned</span><External url={release.url}>View original release</External></div><article className="studio-document-preview workspace-spaced"><p className="workspace-notes">{release.body || 'No release notes provided.'}</p></article></DetailDialog>}</div>;
}
