import { useCallback, useEffect, useRef, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Download, ExternalLink, FileCode2, Folder, GitBranch, KeyRound, Link2, RefreshCw, Search, Unplug } from 'lucide-react';
import type { DashboardData } from '../../lib/dashboard-data';
import { safeExternalUrl } from '../../lib/dashboard-data';
import type { CommitDetail, InsightItem, Inspection, IntegrationProvider, IntegrationStatus, RepositoryFiles, ResourcePage } from '../../lib/integration-types';
import { downloadText, errorMessage, workspaceRequest } from '../../lib/workspace-api';

const labels = { github: 'GitHub', figma: 'Figma', miro: 'Miro' };
type AccessMode = 'public' | 'oauth' | 'token';
function OutsideLink({ url, label = 'Open' }: { url?: string; label?: string }) {
  const safe = safeExternalUrl(url); return safe ? <a className="dash-text-link" href={safe} target="_blank" rel="noreferrer">{label}<ExternalLink size={13} /></a> : null;
}

export default function IntegrationWorkspace({ view, data, onChanged }: { view: string; data: DashboardData; onChanged: () => Promise<void> }) {
  const location = useLocation();
  const connectedProvider = new URLSearchParams(location.search).get('connected');
  const initialProvider = connectedProvider === 'github' || connectedProvider === 'figma' || connectedProvider === 'miro' ? connectedProvider : view === 'figma' ? 'figma' : view === 'miro' ? 'miro' : 'github';
  const [provider, setProvider] = useState<IntegrationProvider>(initialProvider);
  const [status, setStatus] = useState<IntegrationStatus>({ connections: [], oauth: { github: false, figma: false, miro: false } });
  const [accessModes, setAccessModes] = useState<Partial<Record<IntegrationProvider, AccessMode>>>({});
  const connection = status.connections.find(item => item.provider === provider);
  const access = accessModes[provider] || connection?.mode || 'oauth';
  const authorized = Boolean(connection && (provider !== 'github' || connection.mode === access));
  const setAccess = (mode: AccessMode) => setAccessModes(current => ({ ...current, [provider]: mode }));
  const [token, setToken] = useState(''); const [target, setTarget] = useState(() => new URLSearchParams(location.search).get('target') || '');
  const [branch, setBranch] = useState(''); const [days, setDays] = useState('30'); const [parentId, setParentId] = useState(''); const [level, setLevel] = useState('projects');
  const [resources, setResources] = useState<ResourcePage | null>(null); const [report, setReport] = useState<Inspection | null>(null);
  const [files, setFiles] = useState<RepositoryFiles | null>(null); const [commit, setCommit] = useState<CommitDetail | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [search, setSearch] = useState('');
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const loadStatus = useCallback(async () => {
    try { const result = await workspaceRequest<IntegrationStatus>('integrations', { action: 'status' }); if (mounted.current) setStatus(result); }
    catch (cause) { if (mounted.current) setError(errorMessage(cause)); }
  }, []);
  useEffect(() => { const timer = setTimeout(() => void loadStatus(), 0); return () => clearTimeout(timer); }, [loadStatus]);
  const connectionKey = connection ? `${connection.mode}:${connection.account}:${connection.updated_at}` : '';
  useEffect(() => {
    if (!connectionKey || provider === 'figma' || access === 'public' || !authorized) return;
    const controller = new AbortController();
    const timer = setTimeout(() => {
      setBusy('list'); setError('');
      void workspaceRequest<ResourcePage>('integrations', { action: 'list', provider, access }, controller.signal)
        .then(result => { if (!controller.signal.aborted) setResources(result); })
        .catch(cause => { if (!controller.signal.aborted) setError(errorMessage(cause)); })
        .finally(() => { if (!controller.signal.aborted) setBusy(''); });
    }, 0);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [provider, access, connectionKey, authorized]);
  const operation = async (name: string, work: () => Promise<void>) => {
    setBusy(name); setError(''); setNotice('');
    try { await work(); } catch (cause) { if (mounted.current) setError(errorMessage(cause)); }
    finally { if (mounted.current) setBusy(''); }
  };
  const request = <T,>(action: string, extra: Record<string, unknown> = {}) => workspaceRequest<T>('integrations', { action, provider, access: provider === 'github' ? access : 'connected', target, branch, days, ...extra });
  const inspect = (extra: Record<string, unknown> = {}) => operation('inspect', async () => {
    const result = await request<Inspection>('inspect', extra); if (!mounted.current) return;
    setReport(result); setFiles(null); setCommit(null); if (result.branch) setBranch(result.branch);
  });
  const list = (extra: Record<string, unknown> = {}) => operation('list', async () => { const result = await request<ResourcePage>('list', { parentId, level, ...extra }); if (mounted.current) setResources(result); });
  const selectResource = (item: InsightItem) => {
    if (provider === 'figma' && item.kind === 'project') { setParentId(item.id); setLevel('files'); void list({ parentId: item.id, level: 'files' }); return; }
    const value = provider === 'github' ? item.title : item.url || item.id;
    setTarget(value); setBranch(''); void inspect({ target: value, branch: '' });
  };
  const loadFiles = (path = '') => operation('files', async () => { const result = await request<RepositoryFiles>('files', { target: report?.repository || target, branch: report?.branch || branch, path }); if (mounted.current) setFiles(result); });
  const query = new URLSearchParams(location.search);
  const linkedField = provider === 'github' ? 'github_repo' : provider === 'figma' ? 'figma_url' : 'miro_url';
  const choices = provider === 'github' ? [{ id: 'oauth', title: 'GitHub authorization', text: 'Connect your GitHub account and browse your authorized repositories.' }, { id: 'public', title: 'Public repository', text: 'Inspect any public GitHub repository by URL.' }, { id: 'token', title: 'Personal access token', text: 'Optional: connect public/private repositories with a scoped PAT.' }] : [{ id: 'oauth', title: `${labels[provider]} authorization`, text: 'Connect your own account through the provider consent screen.' }, { id: 'token', title: 'Access token / API token', text: 'Optional: use a token with read access to your files or boards.' }];
  return <div className="workspace-stack">
    <section className="dash-panel"><div className="dash-panel-heading"><div><h2>Connected project intelligence</h2><p>Inspect your repositories, designs, and boards using the permissions granted by your account.</p></div><button className="dash-button" disabled={!!busy} onClick={() => void loadStatus()}><RefreshCw size={15} />Connections</button></div><div className="workspace-content">
      {connectedProvider === provider && connection?.mode === 'oauth' && <div className="dash-alert" role="status">{labels[provider]} connected to your account.{provider === 'figma' ? ' Choose a linked design or enter your team/project ID to browse files.' : ' Browse the resources authorized for this account below.'}</div>}
      {query.get('connection_error') && <div className="dash-alert dash-alert-error" role="alert">{query.get('connection_error')}</div>}
      {view === 'integrations' && <div className="workspace-metrics">{(['github', 'figma', 'miro'] as const).map(item => { const saved = status.connections.find(row => row.provider === item); return <div key={item}><span>{labels[item]}</span><strong>{saved ? 'Connected' : 'Not connected'}</strong><small className="workspace-muted">{saved?.account || (item === 'github' ? 'Public repository inspection available' : 'Connect to inspect files or boards')}</small></div>; })}</div>}
      <div className="workspace-tabs" role="tablist" aria-label="Integration provider">{(['github', 'figma', 'miro'] as const).map(item => <button key={item} role="tab" aria-selected={provider === item} disabled={!!busy} onClick={() => { setProvider(item); setTarget(''); setBranch(''); setToken(''); setResources(null); setReport(null); setFiles(null); setCommit(null); setError(''); }}>{labels[item]}{status.connections.some(row => row.provider === item) && <span className="workspace-dot" />}</button>)}</div>
      {error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}{notice && <div className="dash-alert" role="status">{notice}</div>}
      <div className="workspace-options">{choices.map(choice => <button key={choice.id} disabled={!!busy} className={access === choice.id || (provider !== 'github' && access === 'public' && choice.id === 'oauth') ? 'selected' : ''} aria-pressed={access === choice.id} onClick={() => { setAccess(choice.id as typeof access); setReport(null); setResources(null); setFiles(null); setCommit(null); }}><strong>{choice.title}</strong><span>{choice.text}</span></button>)}</div>
      {connection && <div className="workspace-callout"><Link2 size={20} /><div><strong>{connection.account}</strong><p>Connected with {connection.mode === 'oauth' ? 'authorization' : 'an access token'} · Updated {new Date(connection.updated_at).toLocaleString()}{connection.expires_at && ` · Expires ${new Date(connection.expires_at).toLocaleString()}`}</p></div><button className="dash-button" disabled={!!busy} onClick={() => void operation('disconnect', async () => { await request('disconnect'); setReport(null); setResources(null); setFiles(null); setCommit(null); await loadStatus(); await onChanged(); setNotice('Connection removed from PlacePMS. You can also revoke the app or token in the provider settings.'); })}><Unplug size={14} />Disconnect</button></div>}
      {access === 'oauth' && <div className="workspace-callout"><div><strong>Connect your {labels[provider]} account</strong><p>{status.oauth[provider] ? `Sign in on ${labels[provider]} and authorize PlacePMS. Only resources permitted by your account will be available here.` : `The PlacePMS administrator must finish the one-time ${labels[provider]} app setup. Users do not need to create their own OAuth apps.`}</p></div><button className="dash-button dash-button-primary" disabled={!!busy || !status.oauth[provider]} onClick={() => void operation('authorize', async () => { const result = await request<{ url: string }>('connect-oauth'); window.location.assign(result.url); })}>{connection?.mode === 'oauth' ? 'Reconnect' : 'Connect'} {labels[provider]}</button></div>}
      {access === 'token' && <form className="dash-form workspace-token-form" onSubmit={event => { event.preventDefault(); void operation('connect', async () => { const result = await request<{ account: string }>('connect-token', { token }); setToken(''); await loadStatus(); await onChanged(); setNotice(`Connected as ${result.account}.`); }); }}><label>{labels[provider]} access token<input type="password" autoComplete="off" required minLength={10} maxLength={4096} value={token} onChange={event => setToken(event.target.value)} placeholder={provider === 'github' ? 'Fine-grained PAT or classic PAT' : 'Paste your personal/API access token'} /></label><p className="workspace-muted">{provider === 'github' ? 'Use read-only repository access: Metadata, Contents, Issues, and Pull requests. Authorize organization SSO when required.' : provider === 'figma' ? 'Required scopes: current_user:read, file_content:read. Add file_versions:read, file_comments:read, and projects:read for those views.' : 'Use a Miro app access token with boards:read for your authorized team.'} Tokens are encrypted on the server and never returned to your browser.</p><button className="dash-button dash-button-primary" disabled={!!busy}><KeyRound size={15} />{busy === 'connect' ? 'Connecting…' : 'Verify & connect'}</button></form>}
      <form className="dash-form" onSubmit={event => { event.preventDefault(); void inspect(); }}><label>{provider === 'github' ? 'Repository URL or owner/repository' : provider === 'figma' ? 'Figma file URL or file key' : 'Miro board URL or board ID'}<input required disabled={!!busy} value={target} onChange={event => { setTarget(event.target.value); setBranch(''); setReport(null); setFiles(null); setCommit(null); }} placeholder={provider === 'github' ? 'https://github.com/owner/repository' : provider === 'figma' ? 'https://www.figma.com/design/…' : 'https://miro.com/app/board/…'} /></label>
        {provider === 'github' && <div className="dash-form-grid"><label>Branch<input disabled={!!busy} value={branch} onChange={event => { setBranch(event.target.value); setReport(null); setFiles(null); setCommit(null); }} list="repository-branches" placeholder="Default branch" /><datalist id="repository-branches">{report?.branches?.map(name => <option key={name} value={name} />)}</datalist></label><label>Commit window<select disabled={!!busy} value={days} onChange={event => { setDays(event.target.value); setReport(null); setFiles(null); setCommit(null); }}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option></select></label></div>}
        <div className="workspace-actions"><button className="dash-button dash-button-primary" disabled={!!busy || ((provider !== 'github' || access !== 'public') && !authorized)}><Search size={15} />{busy === 'inspect' ? 'Inspecting…' : `Inspect ${provider === 'github' ? 'repository' : provider === 'figma' ? 'design' : 'board'}`}</button>{authorized && (provider !== 'github' || access !== 'public') && <button type="button" className="dash-button" disabled={!!busy} onClick={() => void list()}>Browse my {provider === 'github' ? 'repositories' : provider === 'figma' ? level : 'boards'}</button>}</div>
      </form>
      {provider === 'figma' && <div className="dash-form dash-form-grid workspace-spaced"><label>Figma team / project ID<input value={parentId} onChange={event => setParentId(event.target.value)} placeholder="Numeric ID from your Figma URL" /></label><label>Browse<select value={level} onChange={event => setLevel(event.target.value)}><option value="projects">Team projects</option><option value="files">Project files</option></select></label></div>}
      {data.squads.some(project => project[linkedField]) && <div className="workspace-linked"><strong>Linked to your projects</strong>{data.squads.filter(project => project[linkedField]).map(project => <button key={project.id} className="dash-button" disabled={!!busy || (!authorized && !(provider === 'github' && access === 'public'))} onClick={() => { setTarget(project[linkedField]!); setBranch(''); void inspect({ target: project[linkedField], branch: '' }); }}>{project.title}</button>)}</div>}
    </div></section>
    {resources && <section className="dash-panel"><div className="dash-panel-heading"><h2>Your accessible {provider === 'github' ? 'repositories' : provider === 'figma' ? level : 'boards'}</h2><input className="workspace-input" aria-label="Filter connected resources" placeholder="Filter this page…" value={search} onChange={event => setSearch(event.target.value)} /></div><div className="workspace-content workspace-list">{resources.items.filter(item => `${item.title} ${item.description}`.toLowerCase().includes(search.toLowerCase())).map(item => <article className="workspace-list-item" key={item.id}><div><button className="workspace-title-button" disabled={!!busy} onClick={() => selectResource(item)}>{item.title}</button><p>{item.kind} · {item.description}</p></div><OutsideLink url={item.url} /></article>)}{!resources.items.length && <p>No accessible resources were returned. Check your token permissions and selected team.</p>}{(resources.nextPage || resources.nextCursor) && <button className="dash-button" disabled={!!busy} onClick={() => void list({ page: resources.nextPage, cursor: resources.nextCursor })}>Next page</button>}</div></section>}
    {report && <section className="dash-panel"><div className="dash-panel-heading"><div><h2>{report.title}</h2><p>{report.description}</p></div><div className="workspace-actions"><OutsideLink url={report.url} /><button className="dash-button" onClick={() => downloadText(`${provider}-inspection.json`, JSON.stringify(report, null, 2), 'application/json')}><Download size={15} />Export analysis</button></div></div><div className="workspace-content">
      <div className="workspace-metrics">{report.metrics.map(metric => <div key={metric.label}><span>{metric.label}</span><strong>{metric.value === '' ? '—' : metric.value}</strong></div>)}</div>
      {report.sampleNotice && <p className="workspace-muted">{report.sampleNotice}</p>}{report.warnings.map(warning => <div className="dash-alert dash-alert-error" key={warning}>{warning}</div>)}
      {provider === 'github' && <button className="dash-button workspace-spaced" disabled={!!busy} onClick={() => void loadFiles()}><Folder size={15} />Browse repository files</button>}
      {report.sections.map(section => <details className="workspace-section" key={section.title} open={['Commit history', 'Pages', 'Board items', 'Languages (bytes)'].includes(section.title)}><summary>{section.title}<span>{section.items.length}</span></summary><div className="workspace-list">{section.items.length ? section.items.map(item => <article className="workspace-list-item" key={item.id}><div>{item.kind === 'commit' ? <button className="workspace-title-button" disabled={!!busy} onClick={() => void operation('commit', async () => { const result = await request<CommitDetail>('commit', { target: report.repository, sha: item.id }); if (mounted.current) setCommit(result); })}>{item.title}</button> : <h3>{item.title}</h3>}{item.description && <p>{item.description}</p>}{item.date && <small>{new Date(item.date).toLocaleString()}</small>}{item.value !== undefined && <div className="workspace-bar"><span style={{ width: `${Math.max(1, item.value / Math.max(1, ...section.items.map(row => row.value || 0)) * 100)}%` }} /></div>}</div>{item.value !== undefined && <strong>{item.value.toLocaleString()}</strong>}<OutsideLink url={item.url} /></article>) : <p className="workspace-muted">No records returned for this section.</p>}</div></details>)}
      {report.nextPage && <button className="dash-button" disabled={!!busy} onClick={() => void inspect({ page: report.nextPage })}>Analyze next 100 commits</button>}{report.nextCursor && <button className="dash-button" disabled={!!busy} onClick={() => void inspect({ cursor: report.nextCursor })}>Next page of board items</button>}
    </div></section>}
    {files && <section className="dash-panel"><div className="dash-panel-heading"><h2><FileCode2 size={18} /> {files.path || 'Repository root'}</h2><div className="workspace-actions"><button className="dash-button" disabled={!!busy} onClick={() => void loadFiles(files.path.split('/').slice(0, -1).join('/'))}>Up a directory</button><OutsideLink url={files.url} label="View on GitHub" /></div></div><div className="workspace-content">{files.items?.map(item => <button className="workspace-file" key={item.id} disabled={!!busy} onClick={() => void loadFiles(item.path)}>{item.kind === 'dir' ? <Folder size={16} /> : <FileCode2 size={16} />}{item.title}<small>{item.kind === 'file' ? `${item.value?.toLocaleString()} bytes` : 'Directory'}</small></button>)}{files.binary ? <p>Binary files and files larger than 1 MB can be viewed on GitHub.</p> : files.text !== undefined && <pre className="workspace-code">{files.text}</pre>}</div></section>}
    {commit && <section className="dash-panel"><div className="dash-panel-heading"><div><h2><GitBranch size={18} /> Commit {commit.sha.slice(0, 7)}</h2><p>{commit.author} · {new Date(commit.date).toLocaleString()}</p></div><OutsideLink url={commit.url} /></div><div className="workspace-content"><p>{commit.message}</p><div className="workspace-actions"><span className="workspace-added">+{commit.additions} additions</span><span className="workspace-removed">−{commit.deletions} deletions</span><span>{commit.files.length} files returned</span></div>{commit.truncated && <p className="workspace-muted">Large commits are limited to 100 files and 50,000 characters per patch. See GitHub for the full commit.</p>}{commit.files.map(file => <details className="workspace-section" key={file.name}><summary>{file.name}<span>{file.status} · +{file.additions} / −{file.deletions}</span></summary><pre className="workspace-code">{file.patch || 'No text diff available for this file.'}</pre></details>)}</div></section>}
  </div>;
}
