import { useCallback, useEffect, useRef, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Download, ExternalLink, FileCode2, Folder, GitBranch, KeyRound, Layers3, LayoutDashboard, Link2, RefreshCw, Search, Unplug } from 'lucide-react';
import type { DashboardData } from '../../lib/dashboard-data';
import { safeExternalUrl } from '../../lib/dashboard-data';
import type { CommitDetail, GitHubStatsPage, InsightItem, Inspection, IntegrationProvider, IntegrationStatus, RepositoryFiles, ResourcePage } from '../../lib/integration-types';
import { applyGitHubStats, formatGitHubDate, mergeGitHubAnalysis } from '../../lib/github-analytics';
import { downloadText, errorMessage, workspaceRequest } from '../../lib/workspace-api';
import GitHubRepositoryAnalysis from './GitHubRepositoryAnalysis';
import { CodeViewer, DetailDialog, RecordPager, WorkspaceSections } from './WorkspaceUI';

const labels = { github: 'GitHub', figma: 'Figma', miro: 'Miro' }; const icons = { github: GitBranch, figma: Layers3, miro: LayoutDashboard };
type AccessMode = 'public' | 'oauth' | 'token';
function OutsideLink({ url, label = 'Open' }: { url?: string; label?: string }) { const safe = safeExternalUrl(url); return safe ? <a className="dash-text-link" href={safe} target="_blank" rel="noreferrer">{label}<ExternalLink size={13} /></a> : null; }

export default function IntegrationWorkspace({ view, data, onChanged }: { view: string; data: DashboardData; onChanged: () => Promise<void> }) {
  const location = useLocation(); const query = new URLSearchParams(location.search); const connectedProvider = query.get('connected');
  const initialProvider = connectedProvider === 'github' || connectedProvider === 'figma' || connectedProvider === 'miro' ? connectedProvider : view === 'figma' ? 'figma' : view === 'miro' ? 'miro' : 'github';
  const [provider, setProvider] = useState<IntegrationProvider>(initialProvider); const [status, setStatus] = useState<IntegrationStatus>({ connections: [], oauth: { github: false, figma: false, miro: false } });
  const [accessModes, setAccessModes] = useState<Partial<Record<IntegrationProvider, AccessMode>>>({}); const connection = status.connections.find(item => item.provider === provider); const access = accessModes[provider] || connection?.mode || 'oauth';
  const authorized = Boolean(connection && (provider !== 'github' || connection.mode === access)); const setAccess = (mode: AccessMode) => setAccessModes(current => ({ ...current, [provider]: mode }));
  const [token, setToken] = useState(''); const [target, setTarget] = useState(query.get('target') || ''); const [branch, setBranch] = useState(''); const [days, setDays] = useState('30'); const [parentId, setParentId] = useState(''); const [level, setLevel] = useState('projects');
  const [resources, setResources] = useState<ResourcePage | null>(null); const [report, setReport] = useState<Inspection | null>(null); const [files, setFiles] = useState<RepositoryFiles | null>(null); const [commit, setCommit] = useState<CommitDetail | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [search, setSearch] = useState(''); const [screen, setScreen] = useState('inspect');
  const [resourcePage, setResourcePage] = useState(1); const [filePage, setFilePage] = useState(1); const [section, setSection] = useState('0'); const [inspector, setInspector] = useState<'files' | 'commit' | null>(null); const [commitTab, setCommitTab] = useState('diff'); const [selectedFile, setSelectedFile] = useState('');
  const [analysisProgress, setAnalysisProgress] = useState(''); const analysisAbort = useRef<AbortController | null>(null); const mounted = useRef(true);
  const [inspectorTrigger, setInspectorTrigger] = useState<HTMLElement | null>(null);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; analysisAbort.current?.abort(); }; }, []);
  const loadStatus = useCallback(async () => { try { const result = await workspaceRequest<IntegrationStatus>('integrations', { action: 'status' }); if (mounted.current) setStatus(result); } catch (cause) { if (mounted.current) setError(errorMessage(cause)); } }, []);
  useEffect(() => { const timer = setTimeout(() => void loadStatus(), 0); return () => clearTimeout(timer); }, [loadStatus]);
  const connectionKey = connection ? `${connection.mode}:${connection.account}:${connection.updated_at}` : '';
  useEffect(() => {
    if (!connectionKey || provider === 'figma' || access === 'public' || !authorized) return; const controller = new AbortController();
    const timer = setTimeout(() => { setBusy('list'); setError(''); void workspaceRequest<ResourcePage>('integrations', { action: 'list', provider, access }, controller.signal).then(result => { if (!controller.signal.aborted) { setResources(result); setResourcePage(1); } }).catch(cause => { if (!controller.signal.aborted) setError(errorMessage(cause)); }).finally(() => { if (!controller.signal.aborted) setBusy(''); }); }, 0);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [provider, access, connectionKey, authorized]);
  const operation = async (name: string, work: () => Promise<void>) => { if ((name === 'commit' || name === 'files') && !inspector) setInspectorTrigger(document.activeElement as HTMLElement); setBusy(name); setError(''); setNotice(''); try { await work(); } catch (cause) { if (mounted.current && !analysisAbort.current?.signal.aborted) setError(errorMessage(cause)); } finally { if (mounted.current) setBusy(''); } };
  const request = <T,>(action: string, extra: Record<string, unknown> = {}, signal?: AbortSignal) => workspaceRequest<T>('integrations', { action, provider, access: provider === 'github' ? access : 'connected', target, branch, days, ...extra }, signal);
  const inspect = (extra: Record<string, unknown> = {}) => operation('inspect', async () => {
    const result = await request<Inspection>('inspect', extra); if (!mounted.current) return;
    setReport(result); setFiles(null); setCommit(null); setInspector(null); setAnalysisProgress(''); setScreen('analysis'); setSection('0');
    if (result.branch) setBranch(result.branch);
    document.getElementById('workspace-main')?.scrollTo({ top: 0 });
  });
  const analysisOperation = async (name: string, work: (signal: AbortSignal) => Promise<void>) => { const controller = new AbortController(); analysisAbort.current = controller; await operation(name, () => work(controller.signal)); if (controller.signal.aborted && mounted.current) setAnalysisProgress('Analysis stopped. Loaded results have been kept.'); if (analysisAbort.current === controller) analysisAbort.current = null; };
  const loadHistory = (all: boolean) => { const initial = report; if (!initial?.github) return; void analysisOperation('history', async signal => {
    let analysis = initial.github!;
    for (let count = 0; count < (all ? 10 : 1) && analysis.nextPage; count++) { setAnalysisProgress(`Loading history page ${analysis.nextPage}… ${analysis.commits.length} commits retained.`); const next = await request<Inspection>('inspect', { target: initial.repository, branch: analysis.branch, days: analysis.window.days, until: analysis.window.until, page: analysis.nextPage }, signal); if (signal.aborted || !mounted.current) return; if (!next.github) throw new Error('GitHub returned an incomplete analysis. Please refresh and retry.'); analysis = mergeGitHubAnalysis(analysis, next.github); const merged = analysis; setReport(current => current ? { ...current, github: merged, nextPage: merged.nextPage, warnings: [...new Set([...current.warnings, ...next.warnings])] } : current); }
    if (mounted.current && !signal.aborted) setAnalysisProgress(`${analysis.commits.length} unique commits loaded${analysis.nextPage ? '. More history is available.' : '.'}`);
  }); };
  const analyzeChanges = () => { const initial = report; if (!initial?.github) return; void analysisOperation('stats', async signal => {
    const pending = initial.github!.commits.filter(item => !item.stats); let measured = initial.github!.commits.length - pending.length;
    for (let offset = 0; offset < pending.length; offset += 10) { setAnalysisProgress(`Reading change statistics… ${measured}/${initial.github!.commits.length} commits analyzed.`); const result = await request<GitHubStatsPage>('commit-stats', { target: initial.repository, shas: pending.slice(offset, offset + 10).map(item => item.sha) }, signal); if (signal.aborted || !mounted.current) return; setReport(current => current?.github ? { ...current, github: applyGitHubStats(current.github, result) } : current); measured += result.commits.length; setAnalysisProgress(`Change statistics loaded for ${measured}/${initial.github!.commits.length} commits.`); if (result.errors.length) throw new Error(`Change analysis paused at ${result.errors[0].sha.slice(0, 7)}: ${result.errors[0].message} Loaded statistics have been kept; retry to continue.`); }
  }); };
  const loadCommit = (sha: string) => void operation('commit', async () => { const result = await request<CommitDetail>('commit', { target: report?.repository || target, sha }); if (!mounted.current) return; setCommit(result); setInspector('commit'); setCommitTab('diff'); setSelectedFile(result.files[0]?.name || ''); setFilePage(1); setReport(current => current?.github ? { ...current, github: applyGitHubStats(current.github, { commits: [{ sha: result.sha, stats: { additions: result.additions, deletions: result.deletions, files: result.files.map(file => ({ name: file.name, status: file.status, additions: file.additions, deletions: file.deletions })), filesTruncated: result.truncated } }], errors: [] }) } : current); });
  const clearInspection = () => { setReport(null); setFiles(null); setCommit(null); setInspector(null); setAnalysisProgress(''); };
  const list = (extra: Record<string, unknown> = {}) => operation('list', async () => { const result = await request<ResourcePage>('list', { parentId, level, ...extra }); if (mounted.current) { setResources(result); setResourcePage(1); setScreen('browse'); } });
  const selectResource = (item: InsightItem) => { if (provider === 'figma' && item.kind === 'project') { setParentId(item.id); setLevel('files'); void list({ parentId: item.id, level: 'files' }); return; } const value = provider === 'github' ? item.title : item.url || item.id; setTarget(value); setBranch(''); void inspect({ target: value, branch: '' }); };
  const loadFiles = (path = '') => operation('files', async () => { const result = await request<RepositoryFiles>('files', { target: report?.repository || target, branch: report?.branch || branch, path }); if (mounted.current) { setFiles(result); setFilePage(1); setInspector('files'); } });
  const changeProvider = (value: IntegrationProvider) => { setProvider(value); setTarget(''); setBranch(''); setToken(''); setResources(null); clearInspection(); setError(''); setNotice(''); setSearch(''); setScreen('inspect'); };
  const linkedField = provider === 'github' ? 'github_repo' : provider === 'figma' ? 'figma_url' : 'miro_url'; const ProviderIcon = icons[provider];
  const choices = provider === 'github' ? [{ id: 'oauth', title: 'GitHub authorization', text: 'Your account. Your permitted repositories.' }, { id: 'public', title: 'Public repository', text: 'Inspect a public repository by URL.' }, { id: 'token', title: 'Personal access token', text: 'Connect with scoped read access.' }] : [{ id: 'oauth', title: `${labels[provider]} authorization`, text: 'Connect through the provider consent screen.' }, { id: 'token', title: 'Access token / API token', text: 'Read the files or boards your token permits.' }];
  const filteredResources = resources?.items.filter(item => `${item.title} ${item.description || ''}`.toLowerCase().includes(search.toLowerCase())) || []; const currentResourcePage = Math.min(resourcePage, Math.max(1, Math.ceil(filteredResources.length / 6))); const file = commit?.files.find(item => item.name === selectedFile); const currentFilePage = Math.min(filePage, Math.max(1, Math.ceil((inspector === 'commit' ? commit?.files.length || 0 : files?.items?.length || 0) / 10)));

  const setup = <div className="studio-inspect-grid"><div><div className="workspace-options">{choices.map(choice => <button key={choice.id} disabled={!!busy} className={access === choice.id ? 'selected' : ''} aria-pressed={access === choice.id} onClick={() => { setAccess(choice.id as AccessMode); clearInspection(); setResources(null); }}><strong>{choice.title}</strong><span>{choice.text}</span></button>)}</div>
    {connection && <div className="workspace-callout"><Link2 size={18} /><div><strong>{connection.account}</strong><p>{connection.mode === 'oauth' ? 'Authorized account' : 'Encrypted access token'} · Updated {new Date(connection.updated_at).toLocaleDateString()}</p></div><button className="dash-icon-button" aria-label="Disconnect" title="Disconnect" disabled={!!busy} onClick={() => void operation('disconnect', async () => { await request('disconnect'); clearInspection(); setResources(null); await loadStatus(); await onChanged(); setNotice('Connection removed from PlacePMS. You can also revoke the app or token in the provider settings.'); })}><Unplug size={15} /></button></div>}
    {access === 'oauth' && !authorized && <div className="workspace-callout workspace-spaced"><div><strong>Connect your {labels[provider]} account</strong><p>{status.oauth[provider] ? `Authorize PlacePMS to browse resources allowed by your ${labels[provider]} account.` : `The PlacePMS administrator must finish the one-time ${labels[provider]} application setup.`}</p></div><button className="dash-button dash-button-primary" disabled={!!busy || !status.oauth[provider]} onClick={() => void operation('authorize', async () => { const result = await request<{ url: string }>('connect-oauth'); window.location.assign(result.url); })}>Connect {labels[provider]}</button></div>}
    {access === 'oauth' && authorized && <button className="dash-button workspace-spaced" disabled={!!busy || !status.oauth[provider]} onClick={() => void operation('authorize', async () => { const result = await request<{ url: string }>('connect-oauth'); window.location.assign(result.url); })}>Reconnect {labels[provider]}</button>}
    {access === 'token' && <form className="dash-form workspace-token-form" onSubmit={event => { event.preventDefault(); void operation('connect', async () => { const result = await request<{ account: string }>('connect-token', { token }); setToken(''); await loadStatus(); await onChanged(); setNotice(`Connected as ${result.account}.`); }); }}><label>{labels[provider]} access token<input type="password" autoComplete="off" required minLength={10} maxLength={4096} value={token} onChange={event => setToken(event.target.value)} disabled={!!busy} placeholder="Paste your read-access token" /></label><details className="studio-section-note"><summary>Required access and token storage</summary><p>{provider === 'github' ? 'Read-only Metadata, Contents, Issues, and Pull requests. Authorize organization SSO when required.' : provider === 'figma' ? 'Required: current_user:read and file_content:read. Add file_versions:read, file_comments:read, and projects:read for those views.' : 'Use a Miro app token with boards:read for your authorized team.'} Tokens are encrypted on the server and never returned to your browser.</p></details><button className="dash-button dash-button-primary" disabled={!!busy}><KeyRound size={15} />{busy === 'connect' ? 'Connecting…' : 'Verify & connect'}</button></form>}
  </div><div className="studio-inspect-form"><h3><ProviderIcon size={17} /> Inspect {labels[provider]} evidence</h3><form className="dash-form" onSubmit={event => { event.preventDefault(); void inspect(); }}><label>{provider === 'github' ? 'Repository URL or owner/repository' : provider === 'figma' ? 'Figma file URL or file key' : 'Miro board URL or board ID'}<input required disabled={!!busy} value={target} onChange={event => { setTarget(event.target.value); setBranch(''); clearInspection(); }} placeholder={provider === 'github' ? 'https://github.com/owner/repository' : provider === 'figma' ? 'https://www.figma.com/design/…' : 'https://miro.com/app/board/…'} /></label>{provider === 'github' && <div className="dash-form-grid"><label>Branch<input disabled={!!busy} value={branch} onChange={event => { setBranch(event.target.value); clearInspection(); }} list="repository-branches" placeholder="Default branch" /><datalist id="repository-branches">{report?.branches?.map(name => <option key={name} value={name} />)}</datalist></label><label>Commit window<select disabled={!!busy} value={days} onChange={event => { setDays(event.target.value); clearInspection(); }}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option><option value="all">All history</option></select></label></div>}<div className="workspace-actions"><button className="dash-button dash-button-primary" disabled={!!busy || ((provider !== 'github' || access !== 'public') && !authorized)}><Search size={15} />{busy === 'inspect' ? 'Inspecting…' : `Inspect ${provider === 'github' ? 'repository' : provider === 'figma' ? 'design' : 'board'}`}</button>{authorized && (provider !== 'github' || access !== 'public') && <button type="button" className="dash-button" disabled={!!busy} onClick={() => void list()}>Browse my {provider === 'github' ? 'repositories' : provider === 'figma' ? level : 'boards'}</button>}</div></form>
    {provider === 'figma' && <div className="dash-form dash-form-grid workspace-spaced"><label>Figma team / project ID<input value={parentId} disabled={!!busy} onChange={event => setParentId(event.target.value)} placeholder="Team or project ID" /></label><label>Browse<select value={level} disabled={!!busy} onChange={event => setLevel(event.target.value)}><option value="projects">Team projects</option><option value="files">Project files</option></select></label></div>}
    {data.squads.some(project => project[linkedField]) && <div className="workspace-linked"><strong>Linked to your projects</strong>{data.squads.filter(project => project[linkedField]).map(project => <button key={project.id} className="dash-button" disabled={!!busy || (!authorized && !(provider === 'github' && access === 'public'))} onClick={() => { setTarget(project[linkedField]!); setBranch(''); void inspect({ target: project[linkedField], branch: '' }); }}>{project.title}</button>)}</div>}
  </div></div>;
  const browser = <><div className="workspace-actions"><label className="dash-search"><Search size={15} /><input aria-label="Filter connected resources" placeholder="Filter accessible resources…" value={search} onChange={event => { setSearch(event.target.value); setResourcePage(1); }} /></label><button className="dash-button" disabled={!!busy || !authorized} onClick={() => void list()}><RefreshCw size={14} />Refresh resources</button></div><div className="studio-card-grid workspace-spaced">{filteredResources.slice((currentResourcePage - 1) * 6, currentResourcePage * 6).map(item => <article className="studio-card studio-resource-card" key={item.id}><div className="studio-card-top"><span className="studio-card-icon"><ProviderIcon size={22} /></span><span className="dash-status is-inactive">{item.kind || 'Resource'}</span></div><button disabled={!!busy} onClick={() => selectResource(item)}>{item.title}</button><p className="studio-card-excerpt">{item.description || 'Open a focused analysis of this resource.'}</p><div className="studio-card-actions"><button className="dash-button" disabled={!!busy} aria-label={`Inspect ${item.title}`} onClick={() => selectResource(item)}>Inspect resource</button><OutsideLink url={item.url} /></div></article>)}</div>{!filteredResources.length && <div className="studio-empty"><ProviderIcon size={29} /><h3>{resources ? 'No matching resources' : 'Your connected resources, in one place.'}</h3><p>{resources ? 'Check your filters, token access, or selected team.' : 'Connect your account, then browse its authorized repositories, designs, or boards.'}</p><button className="dash-button" onClick={() => setScreen('inspect')}>Open setup & inspect</button></div>}<RecordPager page={currentResourcePage} total={filteredResources.length} size={6} onChange={setResourcePage} noun="resources" />{(resources?.nextPage || resources?.nextCursor) && <button className="dash-button" disabled={!!busy} onClick={() => void list({ page: resources.nextPage, cursor: resources.nextCursor })}>Next provider page</button>}</>;
  const reportContent = report ? <div className="studio-inspection-report"><div className="dash-panel-heading"><div><h2>{report.title}</h2><p title={report.description}>{report.description}</p></div><div className="workspace-actions studio-report-actions"><OutsideLink url={report.url} /><button className="dash-button" aria-label="Export analysis" title="Export analysis" onClick={() => downloadText(`${provider}-inspection.json`, JSON.stringify(report, null, 2), 'application/json')}><Download size={14} /><span>Export analysis</span></button>{provider === 'github' && <button className="dash-button" aria-label="Browse repository files" title="Browse repository files" disabled={!!busy} onClick={() => void loadFiles()}><Folder size={14} /><span>Browse repository files</span></button>}</div></div>
    {report.warnings.length > 0 && <details className="studio-section-note"><summary>{report.warnings.length} provider notices</summary>{report.warnings.map(warning => <p key={warning}>{warning}</p>)}</details>}{report.sampleNotice && <p className="studio-section-note">{report.sampleNotice}</p>}
    {report.github ? <GitHubRepositoryAnalysis key={`${report.repository}:${report.branch}:${report.github.window.until}`} analysis={report.github} busy={busy} progress={analysisProgress} onCommit={loadCommit} onLoadMore={loadHistory} onAnalyzeChanges={analyzeChanges} onStop={() => analysisAbort.current?.abort()} /> : <><div className="workspace-metrics">{report.metrics.map(metric => <div key={metric.label}><span>{metric.label}</span><strong>{metric.value === '' ? '—' : metric.value}</strong></div>)}</div>{report.sections.length > 0 && <WorkspaceSections label={`${labels[provider]} analysis sections`} value={section} onChange={value => { setSection(value); setResourcePage(1); }} sections={report.sections.map((item, index) => ({ id: String(index), label: item.title, count: item.items.length, content: <GenericInspectionSection title={item.title} items={item.items} busy={busy} onCommit={loadCommit} /> }))} />}{report.nextPage && <button className="dash-button" disabled={!!busy} onClick={() => void inspect({ page: report.nextPage })}>Analyze next 100 commits</button>}{report.nextCursor && <button className="dash-button" disabled={!!busy} onClick={() => void inspect({ cursor: report.nextCursor })}>Next page of board items</button>}</>}
  </div> : <div className="studio-empty"><Search size={27} /><h3>Choose a resource to get started.</h3><p>Your detailed analysis appears here after inspection.</p></div>;
  return <div className={`studio-integration screen-${screen}`}><div className="studio-section-intro"><div><span className="dash-eyebrow">CONNECTED TOOLS / INTELLIGENCE</span><h2>Connected project intelligence</h2><p>Code, designs, and plans. Detailed evidence without the clutter.</p></div><button className="dash-button" disabled={!!busy} onClick={() => void loadStatus()}><RefreshCw size={15} />Connections</button></div><div className="studio-provider-tabs" role="tablist" aria-label="Integration provider">{(['github', 'figma', 'miro'] as const).map(item => { const Icon = icons[item]; return <button key={item} role="tab" aria-label={labels[item]} aria-selected={provider === item} disabled={!!busy} onClick={() => changeProvider(item)}><Icon size={18} /><span>{labels[item]}</span><small aria-hidden="true">{status.connections.some(row => row.provider === item) ? 'CONNECTED' : 'NOT CONNECTED'}</small></button>; })}</div>
    {screen !== 'analysis' && connectedProvider === provider && connection?.mode === 'oauth' && <div className="dash-alert" role="status">{labels[provider]} connected to your account.{provider === 'figma' ? ' Enter your team/project ID to browse files.' : ' Your authorized resources are available in the resource browser.'}</div>}{query.get('connection_error') && <div className="dash-alert dash-alert-error" role="alert">{query.get('connection_error')}</div>}{error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}{notice && <div className="dash-alert" role="status">{notice}</div>}
    <section className="dash-panel"><div className="workspace-content"><WorkspaceSections label="Integration workspace sections" value={screen} onChange={setScreen} sections={[{ id: 'inspect', label: 'Setup & inspect', content: setup }, { id: 'browse', label: 'Resource browser', count: resources?.items.length, content: browser }, { id: 'analysis', label: 'Analysis', disabled: !report, content: reportContent }]} /></div></section>
    {inspector === 'files' && files && <DetailDialog title="Repository file explorer" subtitle={`${report?.repository || target} · ${report?.branch || branch || 'default branch'}`} returnFocus={inspectorTrigger} wide busy={!!busy} onClose={() => setInspector(null)}>
      {error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}
      <div className="studio-file-heading"><strong>{files.path || 'Repository root'}</strong><div className="workspace-actions"><button className="dash-button" disabled={!!busy || !files.path} onClick={() => void loadFiles(files.path.split('/').slice(0, -1).join('/'))}>Up a directory</button><OutsideLink url={files.url} label="View on GitHub" /></div></div>
      {files.items ? <><div className="studio-file-list">{files.items.slice((currentFilePage - 1) * 10, currentFilePage * 10).map(item => <button key={item.id} disabled={!!busy} onClick={() => void loadFiles(item.path)}>{item.kind === 'dir' ? <Folder size={15} /> : <FileCode2 size={15} />}<span>{item.title}<small>{item.kind === 'file' ? `${item.value?.toLocaleString() || 'Unknown'} bytes` : 'Directory'}</small></span><ExternalLink size={12} /></button>)}</div><RecordPager page={currentFilePage} total={files.items.length} size={10} onChange={setFilePage} noun="files" /></> : files.binary ? <div className="studio-empty"><FileCode2 size={28} /><h3>Open this file on GitHub.</h3><p>Binary files and files larger than 1 MB are available in the source repository.</p></div> : files.text !== undefined && <><CodeViewer text={files.text} /><button className="dash-button workspace-spaced" onClick={() => downloadText(files.path.split('/').at(-1) || 'repository-file.txt', files.text || '')}><Download size={14} />Download file</button></>}
    </DetailDialog>}
    {inspector === 'commit' && commit && <DetailDialog title={`Commit ${commit.sha.slice(0, 7)}`} subtitle={commit.message.split('\n')[0] || 'Repository change inspection'} returnFocus={inspectorTrigger} wide busy={!!busy} onClose={() => setInspector(null)}><div id="github-commit-detail"><div className="studio-commit-identities"><p>Authored by {commit.authorIdentity?.name || commit.author}{commit.authorIdentity?.login ? ` (@${commit.authorIdentity.login})` : ''} · {formatGitHubDate(commit.date)}</p>{commit.committerIdentity && <p>Committed by {commit.committerIdentity.name}{commit.committerIdentity.login ? ` (@${commit.committerIdentity.login})` : ''} · {formatGitHubDate(commit.committedAt || '')}</p>}</div><div className="studio-inline-metrics"><span className="workspace-added"><strong>+{commit.additions}</strong>additions</span><span className="workspace-removed"><strong>−{commit.deletions}</strong>deletions</span><span><strong>{commit.files.length}</strong>files returned</span><OutsideLink url={commit.url} label="Open on GitHub" /></div><WorkspaceSections label="Commit inspector sections" value={commitTab} onChange={setCommitTab} sections={[
      { id: 'diff', label: 'Files & diff', count: commit.files.length, content: commit.files.length ? <div className="studio-inspector-layout"><div className="studio-file-list">{commit.files.slice((currentFilePage - 1) * 10, currentFilePage * 10).map(item => <button key={item.name} aria-pressed={selectedFile === item.name} onClick={() => setSelectedFile(item.name)}><FileCode2 size={14} /><span>{item.name}<small>{item.status} · +{item.additions} / −{item.deletions}</small></span></button>)}<RecordPager page={currentFilePage} total={commit.files.length} size={10} onChange={setFilePage} noun="files" /></div><div>{error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}{file && <><div className="studio-file-heading"><strong>Selected file diff</strong><span>+{file.additions} / −{file.deletions}</span></div><CodeViewer text={file.patch || 'No text diff available for this file.'} diff /><button className="dash-button workspace-spaced" disabled={!file.patch} onClick={() => downloadText(`${file.name.replace(/[^a-z0-9._-]/gi, '-')}.patch`, file.patch || '')}><Download size={14} />Download patch</button></>}</div></div> : <p className="workspace-muted">No changed files were returned for this commit.</p> },
      { id: 'identity', label: 'Identity & verification', content: <><dl className="studio-facts">{[['SHA', commit.sha], ['Author', commit.authorIdentity?.name || commit.author], ['Author email', commit.authorIdentity?.email || 'Not provided'], ['Authored (UTC)', formatGitHubDate(commit.date)], ['Committer', commit.committerIdentity?.name || 'Not provided'], ['Committer email', commit.committerIdentity?.email || 'Not provided'], ['Committed (UTC)', formatGitHubDate(commit.committedAt || '')], ['Signature', commit.verified === undefined ? 'Not provided' : commit.verified ? 'Verified signature' : `Not verified${commit.verificationReason ? ` (${commit.verificationReason})` : ''}`]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{!!commit.parents?.length && <div className="workspace-actions workspace-spaced">Parents: {commit.parents.map(sha => <button key={sha} className="dash-button" disabled={!!busy} onClick={() => loadCommit(sha)}>{sha.slice(0, 7)}</button>)}</div>}</> },
      { id: 'message', label: 'Full message', content: <article className="studio-document-preview"><p className="workspace-notes">{commit.message}</p></article> },
    ]} />{commit.truncated && <p className="studio-section-note">Large commits return up to 100 files and 50,000 characters per patch. Open GitHub for the full commit.</p>}</div></DetailDialog>}
  </div>;
}

function GenericInspectionSection({ title, items, busy, onCommit }: { title: string; items: InsightItem[]; busy: string; onCommit: (sha: string) => void }) {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const filtered = items.filter(item => `${item.title} ${item.description || ''}`.toLowerCase().includes(search.toLowerCase())); const current = Math.min(page, Math.max(1, Math.ceil(filtered.length / 6)));
  return <div><div className="studio-file-heading"><strong>{title}</strong><label className="dash-search"><Search size={14} /><input aria-label={`Search ${title}`} placeholder="Search this section…" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /></label></div><div className="studio-card-grid">{filtered.slice((current - 1) * 6, current * 6).map(item => <article className="studio-card" key={item.id}>{item.kind === 'commit' ? <button className="workspace-title-button" disabled={!!busy} onClick={() => onCommit(item.id)}>{item.title}</button> : <h3>{item.title}</h3>}{item.description && <p>{item.description}</p>}{item.date && <small className="studio-card-meta">{new Date(item.date).toLocaleString()}</small>}{item.value !== undefined && <><div className="workspace-bar"><span style={{ width: `${Math.max(1, item.value / Math.max(1, ...items.map(row => row.value || 0)) * 100)}%` }} /></div><p>{item.value.toLocaleString()}</p></>}<div className="studio-card-actions"><OutsideLink url={item.url} /></div></article>)}</div>{!filtered.length && <div className="studio-empty"><h3>No records in this selection.</h3><p>Adjust your search or check the provider notices.</p></div>}<RecordPager page={current} total={filtered.length} size={6} onChange={setPage} noun="records" /></div>;
}
