import { useCallback, useEffect, useRef, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { useSearchParams } from 'react-router-dom';
import { BookOpen, Download, ExternalLink, FileText, FlaskConical, Plus, RefreshCw, Save, Search, Trash2 } from 'lucide-react';
import type { DashboardData } from '../../lib/dashboard-data';
import { getDocuments, safeExternalUrl } from '../../lib/dashboard-data';
import type { LibraryEntry } from '../../lib/workspace-library';
import { supabase } from '../../lib/supabase';
import { downloadText, errorMessage } from '../../lib/workspace-api';
import { DetailDialog, PagedCards, RecordPager, WorkspaceSections } from './WorkspaceUI';

export default function LibraryView({ kind, data, user }: { kind: LibraryEntry['kind']; data: DashboardData; user: User }) {
  const [params] = useSearchParams(); const [entries, setEntries] = useState<LibraryEntry[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [query, setQuery] = useState(''); const [project, setProject] = useState(params.get('project') || '');
  const [page, setPage] = useState(0); const [total, setTotal] = useState(0); const [sort, setSort] = useState('updated_at'); const [tag, setTag] = useState(''); const [tab, setTab] = useState('saved');
  const [editing, setEditing] = useState<Partial<LibraryEntry> | null>(null); const [reading, setReading] = useState<LibraryEntry | null>(null); const [removing, setRemoving] = useState<LibraryEntry | null>(null);
  const requestId = useRef(0); const size = 9; const title = kind === 'research' ? 'Research notebook' : kind === 'resource' ? 'Academic resource library' : 'Project documents'; const Icon = kind === 'research' ? FlaskConical : kind === 'resource' ? BookOpen : FileText;
  const cancelPending = useCallback(() => { requestId.current++; }, []);
  const load = useCallback(async () => {
    if (!supabase) { setLoading(false); setError('Sign in again to load your library.'); return; }
    const current = ++requestId.current; setLoading(true); setError('');
    try {
      let request = supabase.from('workspace_library').select('*', { count: 'exact' }).eq('user_id', user.id).eq('kind', kind).order(sort, { ascending: sort === 'title' }).order('id').range(page * size, page * size + size - 1);
      if (query.trim()) { const pattern = `"%${query.trim().replace(/\\/g, '\\\\').replace(/"/g, '\\"')}%"`; request = request.or(`title.ilike.${pattern},notes.ilike.${pattern},url.ilike.${pattern}`); }
      if (project) request = request.eq('project_id', project); if (tag.trim()) request = request.contains('tags', [tag.trim()]);
      const result = await request; if (current !== requestId.current) return;
      if (result.error) { setEntries([]); setTotal(0); setError(['PGRST205', '42P01'].includes(result.error.code) ? 'Apply the workspace integrations migration in Supabase to enable your library.' : result.error.message); }
      else { setEntries(result.data || []); setTotal(result.count || 0); if (page > 0 && !result.data?.length && (result.count || 0) <= page * size) setPage(Math.max(0, Math.ceil((result.count || 0) / size) - 1)); }
    } catch (cause) { if (current === requestId.current) { setEntries([]); setError(errorMessage(cause)); } }
    finally { if (current === requestId.current) setLoading(false); }
  }, [kind, user.id, page, query, project, sort, tag]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => { clearTimeout(timer); cancelPending(); }; }, [load, cancelPending]);
  const documents = getDocuments(data.milestones.filter(task => !project || task.squad_id === project)).filter(item => `${item.name} ${item.milestone}`.toLowerCase().includes(query.toLowerCase()));
  const exportEntry = (entry: LibraryEntry) => downloadText(`${entry.title.replace(/[^a-z0-9_-]/gi, '-')}.md`, `# ${entry.title}\n\n${entry.url || ''}\n\n${entry.notes}`);
  const createEntry = (entry: Partial<LibraryEntry> = {}) => { setError(''); setReading(null); setEditing({ kind, title: '', notes: '', tags: [], ...entry }); };
  const saved = <><div className="dash-toolbar workspace-toolbar"><label className="dash-search"><Search size={15} /><input aria-label="Search library" value={query} placeholder="Search titles, notes and URLs…" onChange={event => { setQuery(event.target.value); setPage(0); }} /></label><select className="workspace-input" aria-label="Library project filter" value={project} onChange={event => { setProject(event.target.value); setPage(0); }}><option value="">All projects</option>{data.squads.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input className="workspace-input workspace-tag-filter" aria-label="Library tag filter" placeholder="Exact tag" value={tag} onChange={event => { setTag(event.target.value); setPage(0); }} /><select className="workspace-input" aria-label="Sort library" value={sort} onChange={event => { setSort(event.target.value); setPage(0); }}><option value="updated_at">Recently updated</option><option value="created_at">Recently added</option><option value="title">Title A–Z</option></select></div><div className="workspace-actions"><button className="dash-button" disabled={loading || !entries.length} onClick={() => downloadText(`placepms-${kind}-library.json`, JSON.stringify(entries.map(({ user_id: _owner, ...entry }) => entry), null, 2), 'application/json')}><Download size={14} />Export this page</button>{(query || project || tag) && <button className="dash-text-link" onClick={() => { setQuery(''); setProject(''); setTag(''); setPage(0); }}>Clear filters</button>}<span className="workspace-muted">Private to your account</span></div>
    {loading ? <div className="studio-card-grid workspace-spaced" role="status" aria-label="Loading library">{[1, 2, 3].map(item => <div className="dash-skeleton dash-skeleton-stat" key={item} />)}</div> : entries.length ? <div className="studio-card-grid workspace-spaced">{entries.map(entry => <article className="studio-card" key={entry.id}><div className="studio-card-top"><span className="studio-card-icon"><Icon size={19} /></span>{safeExternalUrl(entry.url) && <a className="dash-icon-button" aria-label={`Open source for ${entry.title}`} href={safeExternalUrl(entry.url)!} target="_blank" rel="noreferrer"><ExternalLink size={15} /></a>}</div><h3>{entry.title}</h3><p className="studio-card-excerpt">{entry.notes || 'A saved reference, ready when you need it.'}</p><div className="dash-tags">{entry.tags.slice(0, 4).map(tag => <span key={tag}>{tag}</span>)}{entry.project_id && <span>{data.squads.find(item => item.id === entry.project_id)?.title || 'Linked project'}</span>}</div><small className="studio-card-meta">Updated {new Date(entry.updated_at).toLocaleDateString()}</small><div className="studio-card-actions"><button className="dash-button" aria-label={`Read ${entry.title}`} onClick={() => setReading(entry)}>Read entry</button><button className="dash-button" disabled={busy} onClick={() => createEntry(entry)}>Edit</button><button className="dash-icon-button workspace-danger" aria-label={`Delete ${entry.title}`} disabled={busy} onClick={() => setRemoving(entry)}><Trash2 size={14} /></button></div></article>)}</div> : !error && <div className="studio-empty"><Icon size={27} /><h3>Your next useful reference starts here</h3><p>No saved {kind} entries match these filters.</p><button className="dash-button" onClick={() => createEntry()}><Plus size={14} />Add your first entry</button></div>}
    <RecordPager page={page + 1} total={total} size={size} onChange={value => setPage(value - 1)} noun="entries" /></>;
  const discovery = kind === 'document' ? <>
    <div className="studio-section-intro"><div><span className="dash-eyebrow">PROJECT EVIDENCE</span><h2>Milestone submission links</h2><p>Documents attached to your team’s deliveries.</p></div><span className="studio-card-icon"><FileText size={24} /></span></div>
    <PagedCards items={documents} noun="documents" render={document => <article className="studio-card"><h3>{document.name}</h3><p>{document.milestone}</p><a className="dash-button workspace-spaced" href={document.url} target="_blank" rel="noreferrer">Open evidence <ExternalLink size={14} /></a></article>} />{!documents.length && <p className="workspace-muted">Attach submission links from a project's milestone editor.</p>}
  </> : <><div className="studio-section-intro"><div><span className="dash-eyebrow">DISCOVER / SAVE / BUILD</span><h2>{kind === 'research' ? 'Give your ideas a strong foundation.' : 'Good references. Better decisions.'}</h2><p>Explore trusted sources, then save the links and notes that matter.</p></div><span className="studio-card-icon"><BookOpen size={25} /></span></div>{kind === 'research' ? <div className="studio-card-grid">{[['Google Scholar', `https://scholar.google.com/scholar?q=${encodeURIComponent(query || data.squads.find(item => item.id === project)?.title || '')}`, 'Search scholarly publications and citations.'], ['arXiv', `https://arxiv.org/search/?query=${encodeURIComponent(query || '')}&searchtype=all`, 'Explore open research and preprints.']].map(([name, url, text]) => <article className="studio-card" key={name}><h3>{name}</h3><p>{text}</p><a className="dash-button workspace-spaced" href={url} target="_blank" rel="noreferrer">Explore source <ExternalLink size={14} /></a></article>)}</div> : <div className="studio-card-grid">{[['MDN Web Docs', 'https://developer.mozilla.org/'], ['GitHub Docs', 'https://docs.github.com/'], ['Figma Developers', 'https://developers.figma.com/'], ['Miro Developers', 'https://developers.miro.com/']].map(([name, url]) => <article className="studio-card" key={name}><h3>{name}</h3><p>Official documentation and developer guidance.</p><button className="dash-button workspace-spaced" onClick={() => createEntry({ title: name, url, tags: ['documentation'] })}>Save {name}</button></article>)}</div>}</>;
  return <section className="dash-panel"><div className="dash-panel-heading"><div><h2>{title}</h2><p>Curate your knowledge. Keep your project context close.</p></div><div className="workspace-actions"><button className="dash-icon-button" aria-label="Refresh library" disabled={loading || busy} onClick={() => void load()}><RefreshCw size={15} /></button><button className="dash-button dash-button-primary" onClick={() => createEntry()}><Plus size={15} />Add {kind}</button></div></div><div className="workspace-content">
    {error && !editing && !removing && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}{notice && <div className="dash-alert" role="status">{notice}</div>}
    <WorkspaceSections label="Library sections" value={tab} onChange={setTab} sections={[{ id: 'saved', label: 'Saved entries', count: total, content: saved }, { id: 'discover', label: kind === 'document' ? 'Delivery evidence' : 'Discover sources', content: discovery }]} />
  </div>
    {editing && <DetailDialog title={editing.id ? 'Edit entry' : 'New entry'} subtitle="Your notes, source, and project context." busy={busy} onClose={() => setEditing(null)}>{error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}<form key={editing.id || editing.title || 'new'} className="dash-form" onSubmit={async event => {
      event.preventDefault(); if (!supabase) return; const form = new FormData(event.currentTarget); const value = (name: string) => String(form.get(name) || '').trim(); const url = value('url');
      if (url && !safeExternalUrl(url)) { setError('Use a valid HTTP or HTTPS URL.'); return; } const selectedProject = value('project');
      if (selectedProject && !data.squads.some(item => item.id === selectedProject)) { setError('Choose one of your projects.'); return; } if (!value('title')) { setError('Enter a title for this entry.'); return; }
      setBusy(true); setError(''); setNotice('');
      try {
        const record = { user_id: user.id, kind, title: value('title'), url: url || null, notes: value('notes'), tags: [...new Set(value('tags').split(',').map(tag => tag.trim()).filter(Boolean))].slice(0, 12), project_id: selectedProject || null, updated_at: new Date().toISOString() };
        const result = editing.id ? await supabase.from('workspace_library').update(record).eq('id', editing.id).eq('user_id', user.id).select('id').single() : await supabase.from('workspace_library').insert(record).select('id').single();
        if (result.error) throw result.error; setEditing(null); setTab('saved'); setNotice(editing.id ? 'Library entry updated.' : 'Library entry saved.'); await load();
      } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); }
    }}><fieldset disabled={busy}><label>Title<input name="title" required maxLength={200} defaultValue={editing.title} /></label><label>URL<input name="url" type="url" defaultValue={editing.url || ''} /></label><div className="dash-form-grid"><label>Project<select name="project" defaultValue={editing.project_id || project}><option value="">General / not linked</option>{data.squads.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Tags (comma-separated)<input name="tags" maxLength={400} defaultValue={editing.tags?.join(', ')} /></label></div><label>Notes / document content<textarea name="notes" rows={7} maxLength={20000} defaultValue={editing.notes} /></label><div className="dash-dialog-actions"><button type="button" className="dash-button" onClick={() => setEditing(null)}>Cancel</button><button className="dash-button dash-button-primary"><Save size={15} />{busy ? 'Saving…' : 'Save entry'}</button></div></fieldset></form></DetailDialog>}
    {reading && <DetailDialog title={reading.title} subtitle={`Updated ${new Date(reading.updated_at).toLocaleString()}`} wide onClose={() => setReading(null)}><div className="workspace-actions">{safeExternalUrl(reading.url) && <a className="dash-button" href={safeExternalUrl(reading.url)!} target="_blank" rel="noreferrer">Open source <ExternalLink size={14} /></a>}<button className="dash-button" onClick={() => exportEntry(reading)}><Download size={14} />Export</button><button className="dash-button dash-button-primary" onClick={() => createEntry(reading)}>Edit entry</button></div><article className="studio-document-preview workspace-spaced"><p className="workspace-notes">{reading.notes || 'No notes added yet.'}</p></article></DetailDialog>}
    {removing && <DetailDialog title="Delete library entry" busy={busy} onClose={() => setRemoving(null)}><p className="workspace-muted">Delete “{removing.title}” from your private library?</p>{error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}<div className="dash-dialog-actions"><button className="dash-button" disabled={busy} onClick={() => setRemoving(null)}>Keep entry</button><button className="dash-button workspace-danger" disabled={busy} onClick={async () => { if (!supabase) return; setBusy(true); setError(''); try { const result = await supabase.from('workspace_library').delete().eq('id', removing.id).eq('user_id', user.id); if (result.error) throw result.error; setRemoving(null); setNotice('Library entry deleted.'); await load(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }}><Trash2 size={14} />Delete entry</button></div></DetailDialog>}
  </section>;
}
