import { useEffect, useState, type FormEvent } from 'react';
import type { User } from '@supabase/supabase-js';
import { Link, useSearchParams } from 'react-router-dom';
import { Download, FolderKanban, GitBranch, GraduationCap, Plus, RefreshCw, Save, Search, Settings2, ShieldCheck, Users } from 'lucide-react';
import type { DashboardData } from '../../lib/dashboard-data';
import type { Inspection } from '../../lib/integration-types';
import { featureLabels, roleLabels, useWorkspaceRoot, workspaceRole, type ManagedAccount, type ManagementSettings, type WorkspaceRole } from '../../lib/workspace-roles';
import { downloadText, errorMessage, workspaceRequest } from '../../lib/workspace-api';
import { DetailDialog, RecordPager } from './WorkspaceUI';
import GitHubRepositoryAnalysis from './GitHubRepositoryAnalysis';

function useManagement<T>(action: string, params: Record<string,unknown>={}) {
  const [result, setResult] = useState<{ key: string; data: T | null; error: string } | null>(null);
  const [revision, setRevision] = useState(0);
  const key = JSON.stringify(params);
  const requestKey = JSON.stringify([action, key, revision]);
  useEffect(() => {
    const controller = new AbortController();
    void workspaceRequest<T>('management', { action, ...JSON.parse(key) }, controller.signal)
      .then(data => { if (!controller.signal.aborted) setResult({ key: requestKey, data, error: '' }); })
      .catch(cause => { if (!controller.signal.aborted) setResult({ key: requestKey, data: null, error: errorMessage(cause) }); });
    return () => controller.abort();
  }, [action, key, requestKey]);
  const current = result?.key === requestKey ? result : null;
  return { data: current?.data ?? null, loading: !current, error: current?.error ?? '', reload: () => setRevision(value => value + 1) };
}
function Feedback({error,loading}:{error:string;loading:boolean}) { return <>{error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}{loading && <p role="status" className="studio-section-note">Loading management data…</p>}</>; }
function Heading({title,description,children}:{title:string;description:string;children?:React.ReactNode}) { return <div className="studio-section-intro"><div><span className="dash-eyebrow">PLACEPMS / MANAGEMENT</span><h2>{title}</h2><p>{description}</p></div>{children}</div>; }

export function ManagementOverview({data,user}:{data:DashboardData;user:User}) {
  const root=useWorkspaceRoot(); const role=workspaceRole(user);
  if (role!=='admin') {
    const assigned=data.squads.filter(project=>project.mentor_id===user.id || project.mentor_id?.toLowerCase()===user.email?.toLowerCase());
    const reviews=data.milestones.filter(task=>task.status==='SUBMITTED' && assigned.some(project=>project.id===task.squad_id));
    return <div className="workspace-stack"><Heading title={`${roleLabels[role]} workspace`} description="Your assigned projects, student deliveries, repository evidence, and mentor reviews." /><div className="intel-metrics"><div className="intel-metric"><span>Assigned projects</span><strong>{assigned.length}</strong><small>Projects assigned to your account</small></div><div className="intel-metric"><span>Awaiting review</span><strong>{reviews.length}</strong><small>Submitted deliveries in assigned projects</small></div><div className="intel-metric"><span>Linked repositories</span><strong>{assigned.filter(project=>project.github_repo).length}</strong><small>Inspect live data or open saved analyses</small></div></div><div className="studio-card-grid">{[['projects','Assigned project workspaces','Open project teams, milestones, documents, and connected tools.'],['students','Student roster','Check student profiles, project membership, progress, scores, and submitted evidence.'],['mentorship','Mentor review queue','Review submitted evidence, give feedback, and record scores.'],['reports','GitHub evidence & AI flags','Read shared repository snapshots and explicit AI commit evidence.']].map(([slug,title,description])=><article className="studio-card" key={slug}><span className="studio-card-icon"><GraduationCap size={22}/></span><h3>{title}</h3><p>{description}</p><Link className="dash-button workspace-spaced" to={`${root}/${slug}`}>Open workspace</Link></article>)}</div></div>;
  }
  return <AdminOverview />;
}
function AdminOverview() {
  const root=useWorkspaceRoot(); const {data,loading,error,reload}=useManagement<{counts:Record<string,number>}>('overview');
  return <div className="workspace-stack"><Heading title="Administration control center" description="Manage people, mentoring, projects, delivery evidence, features, and connected tools."><button className="dash-button" onClick={reload} disabled={loading}><RefreshCw size={14}/>Refresh</button></Heading><Feedback loading={loading} error={error}/>{data && <div className="intel-metrics">{[['accounts','Registered accounts','accounts'],['mentors','Enabled mentors','accounts'],['projects','Project workspaces','projects'],['milestones','Milestones','tasks'],['connections','Provider connections','connections'],['reports','Saved GitHub analyses','reports']].map(([key,label,slug])=><Link className="intel-metric management-metric" key={key} to={`${root}/${slug}`}><span>{label}</span><strong>{data.counts[key]}</strong><small>Open management</small></Link>)}</div>}<div className="studio-card-grid">{[['accounts','Teachers, staff & students','Create accounts, assign roles, enable mentors, reset passwords, and manage access.',Users],['projects','Projects & mentor assignments','Manage all project workspaces, assign mentors, maintain teams, and track deliveries.',FolderKanban],['reports','Repository evidence & AI flags','Review saved GitHub data, declared AI tools, commits, contributors, and delivery signals.',GitBranch],['settings','Feature controls','Manage public registration and GitHub, Figma, Miro, research, documents, and Blackbook availability.',Settings2]].map(([slug,title,description,Icon])=>{const Graphic=Icon as typeof Users; return <article className="studio-card" key={String(slug)}><span className="studio-card-icon"><Graphic size={22}/></span><h3>{String(title)}</h3><p>{String(description)}</p><Link className="dash-button workspace-spaced" to={`${root}/${slug}`}>Open management</Link></article>;})}</div></div>;
}

export default function ManagementWorkspace({view,user,onSaved}:{view:string;user:User;onSaved:(message:string)=>Promise<void>}) {
  if (view==='reports') return <RepositoryReports />;
  if (workspaceRole(user)!=='admin') return <Heading title="Administrator access required" description="This management page is available to administrators."/>;
  if (view==='accounts') return <Accounts user={user} onSaved={onSaved}/>;
  if (view==='settings') return <Settings onSaved={onSaved}/>;
  if (view==='connections') return <ConnectionManagement onSaved={onSaved}/>;
  return <Audit />;
}

function Accounts({user,onSaved}:{user:User;onSaved:(message:string)=>Promise<void>}) {
  const [params]=useSearchParams(); const [role,setRole]=useState(params.get('role') || ''); const [search,setSearch]=useState(''); const [page,setPage]=useState(1);
  const {data,loading,error,reload}=useManagement<{items:ManagedAccount[];total:number}>('accounts.list',{role,search,page});
  const [editing,setEditing]=useState<Partial<ManagedAccount> | null>(null); const [busy,setBusy]=useState(false); const [saveError,setSaveError]=useState(''); const [notice,setNotice]=useState('');
  const act=async(action:string,values:Record<string,unknown>,message:string)=>{setBusy(true);setSaveError('');setNotice('');try{await workspaceRequest('management',{action,...values}); await onSaved(message);reload();setNotice(message);return true;}catch(cause){setSaveError(errorMessage(cause));return false;}finally{setBusy(false);}};
  return <div className="workspace-stack"><Heading title="Accounts & mentors" description="Admin-managed teachers, staff, students, and administrators. Passwords and login codes are emailed only to the account owner."><button className="dash-button dash-button-primary" onClick={()=>{setSaveError('');setEditing({role:'teacher',can_mentor:true,enabled:true,college:String(user.user_metadata.college || '')});}}><Plus size={15}/>Create account</button></Heading><div className="workspace-actions"><label className="dash-search"><Search size={15}/><input aria-label="Search managed accounts" placeholder="Search name or email…" value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}}/></label><select className="workspace-input" aria-label="Filter account role" value={role} onChange={event=>{setRole(event.target.value);setPage(1);}}><option value="">All roles</option>{Object.entries(roleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className="dash-button" onClick={reload} disabled={loading}><RefreshCw size={14}/>Refresh</button></div><Feedback loading={loading} error={error}/>{notice && <div className="dash-alert" role="status">{notice}</div>}{saveError && !editing && <div className="dash-alert dash-alert-error" role="alert">{saveError}</div>}
    {!loading && data && <><div className="studio-card-grid">{data.items.map(account=><article className="studio-card" key={account.id}><div className="studio-card-top"><span className="studio-card-icon"><Users size={20}/></span><span className="dash-status">{account.enabled?roleLabels[account.role]:'Disabled'}</span></div><h3>{account.full_name || account.email}</h3><p>{account.email}</p><small className="studio-card-meta">{account.department || account.college || 'No department'}{account.can_mentor?' · Mentor enabled':''}</small><div className="studio-card-actions"><button className="dash-button" onClick={()=>{setSaveError('');setEditing(account);}}>Manage account</button></div></article>)}</div>{!data.items.length && <div className="studio-empty"><Users size={26}/><h3>No matching accounts</h3><p>Try another role or create a teacher/staff account.</p></div>}<RecordPager page={page} total={data.total} size={20} onChange={setPage} noun="accounts"/></>}
    {editing && <DetailDialog title={editing.id?'Manage account':'Create account'} subtitle={editing.id?editing.email:'An initial login code will be emailed to the owner.'} busy={busy} onClose={()=>setEditing(null)}>{saveError && <div className="dash-alert dash-alert-error" role="alert">{saveError}</div>}<form className="dash-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const values={role:editing.role,full_name:form.get('full_name'),college:form.get('college'),can_mentor:editing.role!=='student' && form.get('can_mentor')==='on',department:String(form.get('department') || ''),...(editing.id?{id:editing.id,enabled:form.get('enabled')==='on'}:{email:form.get('email')})};if(await act(editing.id?'accounts.update':'accounts.create',values,editing.id?'Account details and permissions updated. Role and access changes require a fresh sign-in.':'Account created and first-login email sent.'))setEditing(null);}}><fieldset disabled={busy}>
      <label>Full name<input name="full_name" required maxLength={120} defaultValue={editing.full_name || ''}/></label>{!editing.id && <label>Account email<input name="email" type="email" required maxLength={254}/></label>}<label>Institution<input name="college" required maxLength={200} defaultValue={editing.college || ''}/></label>
      <label>Account role<select name="role" value={editing.role} onChange={event=>setEditing({...editing,role:event.target.value as WorkspaceRole,can_mentor:event.target.value==='student'?false:editing.can_mentor})}>{Object.entries(roleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Department<input name="department" maxLength={120} defaultValue={editing.department || ''}/></label><label className="workspace-checkbox"><input name="can_mentor" type="checkbox" disabled={editing.role==='student'} checked={Boolean(editing.can_mentor) && editing.role!=='student'} onChange={event=>setEditing({...editing,can_mentor:event.target.checked})}/>Eligible for mentor assignment</label>{editing.id && <label className="workspace-checkbox"><input name="enabled" type="checkbox" defaultChecked={editing.enabled}/>Account enabled</label>}<div className="dash-dialog-actions"><button type="button" className="dash-button" onClick={()=>setEditing(null)}>Cancel</button><button className="dash-button dash-button-primary"><Save size={14}/>{editing.id?'Save permissions':'Create & email account'}</button></div></fieldset></form>
      {editing.id && <div className="management-account-actions"><p className="studio-section-note">Account owners choose their own passwords. Administrators never see existing passwords.</p><button className="dash-button" disabled={busy} onClick={()=>void act('accounts.reset',{id:editing.id},'Password recovery email sent to the owner.')}>Send password reset</button><button className="dash-button workspace-danger" disabled={busy || editing.id===user.id} onClick={()=>{if(window.confirm(`Sign ${editing.email} out of every device?`))void act('accounts.revoke',{id:editing.id},'All account sessions revoked.');}}>Sign out all devices</button></div>}
    </DetailDialog>}
  </div>;
}

interface SavedReport {id:string;repository:string;branch:string;project_id:string|null;loaded_commits:number;ai_marked:number;snapshot_at:string;updated_at:string;owner?:{full_name:string;email:string};payload?:Inspection}
function RepositoryReports() {
  const [search,setSearch]=useState('');const [ai,setAI]=useState(false);const [page,setPage]=useState(1);const [selected,setSelected]=useState<SavedReport | null>(null);const [opening,setOpening]=useState('');const [openError,setOpenError]=useState('');
  const {data,loading,error,reload}=useManagement<{items:SavedReport[];total:number}>('reports.list',{page,search,ai_only:ai});
  const open=async(id:string)=>{setOpening(id);setOpenError('');try{setSelected(await workspaceRequest<SavedReport>('management',{action:'reports.get',id}));}catch(cause){setOpenError(errorMessage(cause));}finally{setOpening('');}};
  return <div className="workspace-stack"><Heading title="GitHub evidence & AI flags" description="Saved inspections from real provider responses. Administrators see all; teachers and staff see their own and assigned-project analyses."><button className="dash-button" onClick={reload} disabled={loading}><RefreshCw size={14}/>Refresh</button></Heading>
    <div className="workspace-actions"><label className="dash-search"><Search size={15}/><input aria-label="Search saved repositories" value={search} placeholder="Repository name…" onChange={event=>{setSearch(event.target.value);setPage(1);}}/></label><label className="workspace-checkbox"><input type="checkbox" checked={ai} onChange={event=>{setAI(event.target.checked);setPage(1);}}/>Only analyses with AI-marked commits</label></div><Feedback loading={loading} error={error || openError}/>
    {!loading && data && <><div className="studio-card-grid">{data.items.map(report=><article className="studio-card" key={report.id}><div className="studio-card-top"><span className="studio-card-icon"><GitBranch size={20}/></span><span className="github-badge">{report.ai_marked} AI-marked / {report.loaded_commits} loaded</span></div><h3>{report.repository}</h3><p>{report.branch} · {report.owner?.full_name || report.owner?.email || 'Account inspection'}</p><small className="studio-card-meta">Snapshot {new Date(report.snapshot_at).toLocaleString()}</small><button className="dash-button" disabled={Boolean(opening)} onClick={()=>void open(report.id)}>{opening===report.id?'Opening…':'Inspect saved analysis'}</button></article>)}</div>{!data.items.length && <div className="studio-empty"><GitBranch size={26}/><h3>No matching saved analyses</h3><p>Inspect a repository from a project's Connected tools section to share its evidence with assigned mentors. Administrators also see unlinked inspections.</p></div>}<RecordPager page={page} total={data.total} size={10} onChange={setPage} noun="analyses"/></>}
    {selected?.payload?.github && <DetailDialog title={selected.repository} subtitle="Saved provider snapshot · read-only" wide onClose={()=>setSelected(null)}><p className="studio-section-note">Counts describe the loaded branch/window. Missing AI markers do not establish human authorship. Provider credentials remain private; open live analysis with your own connection.</p><button className="dash-button" onClick={()=>downloadText('saved-github-analysis.json',JSON.stringify(selected.payload,null,2),'application/json')}><Download size={14}/>Export saved analysis</button><GitHubRepositoryAnalysis analysis={selected.payload.github} busy="snapshot" progress="" onCommit={()=>{}} onLoadMore={()=>{}} onAnalyzeChanges={()=>{}} onStop={()=>{}}/></DetailDialog>}
  </div>;
}
function Settings({onSaved}:{onSaved:(message:string)=>Promise<void>}) {
  const {data,loading,error,reload}=useManagement<{settings:ManagementSettings}>('access');const [busy,setBusy]=useState(false);const [saveError,setSaveError]=useState('');
  const save=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setSaveError('');
    try{await workspaceRequest('management',{action:'settings.update',registration_enabled:form.get('registration')==='on',features:Object.fromEntries(Object.keys(featureLabels).map(key=>[key,form.get(key)==='on']))});await onSaved('Feature controls saved.');reload();}
    catch(cause){setSaveError(errorMessage(cause));}finally{setBusy(false);}
  };
  return <div className="workspace-stack"><Heading title="Feature & registration controls" description="Controls apply to students, teachers, and staff. Administrators retain access to manage and re-enable features."/><Feedback loading={loading} error={error}/>{saveError && <div className="dash-alert dash-alert-error" role="alert">{saveError}</div>}
    {data && <section className="dash-panel workspace-content"><form key={JSON.stringify(data.settings)} className="dash-form" onSubmit={save}><fieldset disabled={busy}>
      <label className="workspace-checkbox"><input name="registration" type="checkbox" defaultChecked={data.settings.registration_enabled}/>Allow public account registration</label>
      <div className="management-feature-grid">{Object.entries(featureLabels).map(([key,label])=><label key={key} className="management-feature"><input type="checkbox" name={key} defaultChecked={data.settings.features[key as keyof typeof featureLabels]}/><ShieldCheck size={17}/><span>{label}</span></label>)}</div>
      <button className="dash-button dash-button-primary"><Save size={14}/>Save controls</button>
    </fieldset></form></section>}
  </div>;
}
function ConnectionManagement({onSaved}:{onSaved:(message:string)=>Promise<void>}) {
  const [page,setPage]=useState(1);const {data,loading,error,reload}=useManagement<{items:{user_id:string;provider:string;mode:string;account:string;updated_at:string}[];total:number}>('connections.list',{page});const [busy,setBusy]=useState(false);const [saveError,setSaveError]=useState('');
  const disconnect=async(owner:string,provider:string,account:string)=>{
    if(!window.confirm(`Disconnect ${provider} for ${account}?`))return;setBusy(true);setSaveError('');
    try{await workspaceRequest('management',{action:'connections.disconnect',id:owner,provider});await onSaved('Provider connection removed.');reload();}catch(cause){setSaveError(errorMessage(cause));}finally{setBusy(false);}
  };
  return <div className="workspace-stack"><Heading title="Provider connection management" description="Manage authorized connection metadata and disconnect accounts. Tokens and provider passwords are never exposed."/><Feedback loading={loading} error={error || saveError}/>
    {data && <><div className="studio-card-grid">{data.items.map(connection=><article className="studio-card" key={`${connection.user_id}:${connection.provider}`}><span className="github-badge">{connection.provider} · {connection.mode}</span><h3>{connection.account}</h3><p className="workspace-notes">Account ID: {connection.user_id}</p><small className="studio-card-meta">Updated {new Date(connection.updated_at).toLocaleString()}</small><button className="dash-button workspace-danger" disabled={busy} onClick={()=>void disconnect(connection.user_id,connection.provider,connection.account)}>Disconnect account</button></article>)}</div>{!data.items.length && <p className="studio-section-note">No provider connections exist.</p>}<RecordPager page={page} total={data.total} size={20} onChange={setPage} noun="connections"/></>}
  </div>;
}
function Audit() {
  const [page,setPage]=useState(1);const {data,loading,error}=useManagement<{items:{id:string;actor_id:string;action:string;subject:string;created_at:string}[];total:number}>('audit.list',{page});
  return <div className="workspace-stack"><Heading title="Management activity" description="Recorded account, feature, session, and connection management actions."/><Feedback loading={loading} error={error}/>{data && <><div className="workspace-list">{data.items.map(event=><article className="studio-card" key={event.id}><h3>{event.action.replace(/[._]/g,' ')}</h3><p className="workspace-notes">Subject: {event.subject}</p><small className="studio-card-meta">{new Date(event.created_at).toLocaleString()} · Actor {event.actor_id || 'Removed account'}</small></article>)}</div>{!data.items.length && <p className="studio-section-note">No management actions have been recorded.</p>}<RecordPager page={page} total={data.total} size={20} onChange={setPage} noun="actions"/></>}</div>;
}
