import { useEffect, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { Link, useLocation } from 'react-router-dom';
import { Archive, ArrowLeft, CheckCircle2, Download, ExternalLink, Pencil, Plus, Save, Search, Trash2, Users, X } from 'lucide-react';
import type { DashboardData, Member, Milestone } from '../../lib/dashboard-data';
import { getDocuments, getDashboardStats, isComplete, isInactive, safeExternalUrl } from '../../lib/dashboard-data';
import { downloadText, errorMessage, workspaceRequest } from '../../lib/workspace-api';
import { milestoneCsv } from '../../lib/workspace-insights';

export default function ProjectDetails({ id, data, user, onSaved, onCreate }: { id: string; data: DashboardData; user: User; onSaved: (message: string) => Promise<void>; onCreate: (kind: 'milestone') => void }) {
  const project = data.squads.find(item => item.id === id);
  const location = useLocation();
  const [editing, setEditing] = useState(false);
  const [memberForm, setMemberForm] = useState<Partial<Member> | null>(null);
  const [milestone, setMilestone] = useState<Milestone | null>(null);
  const [review, setReview] = useState<Milestone | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  useEffect(() => {
    if (!location.hash) return;
    let target = '';
    try { target = decodeURIComponent(location.hash.slice(1)); } catch { return; }
    const frame = requestAnimationFrame(() => document.getElementById(target)?.scrollIntoView({ block: 'center' }));
    return () => cancelAnimationFrame(frame);
  }, [location.hash, data.milestones.length]);
  if (!project) return <section className="dash-panel workspace-content"><h2>Project not found</h2><p>You may not have access to this project.</p><Link className="dash-button" to="/dashboard/projects">Back to projects</Link></section>;
  const owner = project.leader_email.toLowerCase() === user.email?.toLowerCase();
  const isMentor = project.mentor_id === user.id || project.mentor_id?.toLowerCase() === user.email?.toLowerCase();
  const inactive = isInactive(project.status);
  const tasks = data.milestones.filter(item => item.squad_id === id); const members = data.members.filter(item => item.squad_id === id);
  const stats = getDashboardStats({ squads: [project], milestones: tasks, members });
  const mutate = async (action: string, values: Record<string, unknown>, message: string) => {
    setBusy(true); setError('');
    try { await workspaceRequest('workspace', { action, projectId: id, ...values }); await onSaved(message); return true; }
    catch (cause) { setError(errorMessage(cause)); return false; } finally { setBusy(false); }
  };
  const fields = (form: HTMLFormElement) => Object.fromEntries(new FormData(form).entries());
  const shownTasks = tasks.filter(task => `${task.name} ${task.phase} ${task.description || ''}`.toLowerCase().includes(query.trim().toLowerCase()));

  return <div className="workspace-stack"><Link className="dash-text-link" to="/dashboard/projects"><ArrowLeft size={15} />All projects</Link>
    {error && <div className="dash-alert dash-alert-error" role="alert">{error}</div>}
    <section className="dash-panel"><div className="dash-panel-heading"><div><h2>{project.title}</h2><p>{project.tagline || project.domain || 'Project workspace'}</p></div><div className="workspace-actions"><span className="dash-status">{project.status || 'Pending'}</span>{owner && <><button className="dash-button" disabled={busy} onClick={() => setEditing(!editing)}><Pencil size={14} />{editing ? 'Cancel editing' : 'Edit project'}</button><button className="dash-button" disabled={busy} onClick={() => void mutate('project.archive', { restore: project.status === 'ARCHIVED' }, project.status === 'ARCHIVED' ? 'Project restored.' : 'Project archived.')}><Archive size={14} />{project.status === 'ARCHIVED' ? 'Restore' : 'Archive'}</button></>}</div></div><div className="workspace-content">
      <p className="workspace-notes">{project.summary || 'Add a summary to describe what your team is building.'}</p><div className="workspace-metrics">{[['Milestone completion', `${stats.completion}%`], ['Pending', stats.pendingTasks], ['Overdue', stats.overdueTasks], ['Completed', stats.completedTasks]].map(([name, value]) => <div key={String(name)}><span>{name}</span><strong>{value}</strong></div>)}</div><p className="workspace-muted">Lead: {project.leader_email} · Mentor: {project.mentor_name || project.mentor_id || 'Not assigned'} · Phase: {project.current_phase || 'Not set'}</p>
      <div className="workspace-linked">{([['github_repo', 'repositories', 'GitHub'], ['figma_url', 'figma', 'Figma'], ['miro_url', 'miro', 'Miro']] as const).map(([field, slug, label]) => safeExternalUrl(project[field]) && <Link className="dash-button" key={field} to={`/dashboard/${slug}?target=${encodeURIComponent(project[field]!)}`}>Inspect {label}<ExternalLink size={13} /></Link>)}<Link className="dash-button" to={`/dashboard/tasks?project=${encodeURIComponent(id)}`}>Project tasks</Link><Link className="dash-button" to={`/dashboard/research?project=${encodeURIComponent(id)}`}>Project research</Link><Link className="dash-button" to={`/dashboard/documents?project=${encodeURIComponent(id)}`}>Project documents</Link><button className="dash-button" disabled={!tasks.length} onClick={() => downloadText('placepms-project-milestones.csv', milestoneCsv(tasks, data), 'text/csv;charset=utf-8')}><Download size={14} />Export evidence</button></div>
      {editing && <form className="dash-form workspace-editor" onSubmit={async event => { event.preventDefault(); const values = fields(event.currentTarget); if (await mutate('project.update', { ...values, clear_mentor: values.clear_mentor === 'on' }, 'Project details updated.')) setEditing(false); }}><fieldset disabled={busy}><label>Project title<input name="title" required maxLength={160} defaultValue={project.title} /></label><div className="dash-form-grid"><label>Tagline<input name="tagline" maxLength={200} defaultValue={project.tagline || ''} /></label><label>Domain<input name="domain" maxLength={120} defaultValue={project.domain || ''} /></label></div><label>Summary<textarea name="summary" rows={4} maxLength={4000} defaultValue={project.summary || ''} /></label><label>Current phase<input name="current_phase" maxLength={120} defaultValue={project.current_phase || ''} /></label><label>GitHub repository URL<input name="github_repo" type="url" maxLength={2000} defaultValue={project.github_repo || ''} /></label><div className="dash-form-grid"><label>Figma URL<input name="figma_url" type="url" maxLength={2000} defaultValue={project.figma_url || ''} /></label><label>Miro URL<input name="miro_url" type="url" maxLength={2000} defaultValue={project.miro_url || ''} /></label></div><label>Assign / replace mentor by registered email<input name="mentor_email" type="email" placeholder="Leave empty to keep the current mentor" /></label><label className="workspace-checkbox"><input name="clear_mentor" type="checkbox" />Remove current mentor</label><button className="dash-button dash-button-primary" disabled={busy}><Save size={14} />Save project</button></fieldset></form>}
    </div></section>
    <section className="dash-panel"><div className="dash-panel-heading"><div><h2><Users size={18} /> Project team</h2><p>Manage team roles and skills. Members can access the project using their registered email.</p></div>{owner && <button className="dash-button" disabled={busy} onClick={() => setMemberForm(memberForm ? null : {})}><Plus size={14} />{memberForm ? 'Cancel member editor' : 'Add member'}</button>}</div><div className="workspace-content">
      {memberForm && <form key={memberForm.id || 'new-member'} className="dash-form workspace-editor" onSubmit={async event => { event.preventDefault(); if (await mutate(memberForm.id ? 'member.update' : 'member.add', { ...fields(event.currentTarget), memberId: memberForm.id }, memberForm.id ? 'Team member updated.' : 'Team member added.')) setMemberForm(null); }}><fieldset disabled={busy}><div className="dash-form-grid"><label>Member name<input name="name" required maxLength={160} defaultValue={memberForm.name || ''} /></label><label>Member email<input name="email" type="email" required maxLength={254} defaultValue={memberForm.email || ''} /></label><label>Team role<input name="role" maxLength={100} placeholder="Developer / Designer / Researcher" defaultValue={memberForm.role || ''} /></label><label>Skills (comma-separated)<input name="skills" maxLength={500} defaultValue={memberForm.skills?.join(', ') || ''} /></label></div><button className="dash-button dash-button-primary" disabled={busy}>Save member</button></fieldset></form>}
      <div className="workspace-list">{members.length ? members.map(member => <article className="workspace-list-item" key={member.id}><div><h3>{member.name}</h3><p>{member.email} · {member.role || 'Member'}</p><div className="dash-tags">{member.skills?.map(skill => <span key={skill}>{skill}</span>)}</div></div>{owner && <div className="workspace-actions"><button className="dash-button" disabled={busy} aria-label={`Edit ${member.name}`} onClick={() => setMemberForm(member)}><Pencil size={14} />Edit</button><button className="dash-button workspace-danger" disabled={busy} aria-label={`Remove ${member.name}`} onClick={() => { if (window.confirm(`Remove ${member.name} from this project?`)) void mutate('member.remove', { memberId: member.id }, 'Team member removed.'); }}><Trash2 size={14} /></button></div>}</article>) : <p className="workspace-muted">No additional team members recorded.</p>}</div>
    </div></section>
    <section className="dash-panel"><div className="dash-panel-heading"><div><h2>Milestones & submissions</h2><p>Plan work, attach delivery evidence, submit, and review in the same project.</p></div><button className="dash-button" disabled={inactive || busy} onClick={() => onCreate('milestone')}><Plus size={14} />Add milestone</button></div><div className="workspace-content">
      <label className="dash-search"><Search size={15} /><input aria-label="Search project milestones" placeholder="Find a milestone or phase…" value={query} onChange={event => setQuery(event.target.value)} /></label>
      {milestone && <form key={milestone.id} className="dash-form workspace-editor" onSubmit={async event => { event.preventDefault(); if (await mutate('milestone.update', { ...fields(event.currentTarget), milestoneId: milestone.id }, 'Milestone and submission links updated.')) setMilestone(null); }}><div className="workspace-actions"><h3>Edit milestone</h3><button type="button" className="dash-icon-button" disabled={busy} aria-label="Close milestone editor" onClick={() => setMilestone(null)}><X size={16} /></button></div><fieldset disabled={busy}><label>Milestone name<input name="name" required maxLength={160} defaultValue={milestone.name} /></label><label>Phase<input name="phase" required maxLength={120} defaultValue={milestone.phase} /></label><label>Description<textarea name="description" rows={3} maxLength={4000} defaultValue={milestone.description || ''} /></label><div className="dash-form-grid"><label>Start date<input name="start_date" type="date" defaultValue={milestone.start_date || ''} /></label><label>Due date<input name="due_date" type="date" defaultValue={milestone.due_date || ''} /></label></div><label>Submission document URLs (one per line)<textarea name="links" rows={4} defaultValue={getDocuments([milestone]).map(item => item.url).join('\n')} /></label><p className="workspace-muted">Attach up to 20 externally hosted HTTP/HTTPS document links.</p><button className="dash-button dash-button-primary" disabled={busy}>Save milestone</button></fieldset></form>}
      {review && <form key={`review-${review.id}`} className="dash-form workspace-editor" onSubmit={async event => { event.preventDefault(); const values = fields(event.currentTarget); if (await mutate('milestone.review', { milestoneId: review.id, ...values, approve: values.decision === 'approve' }, 'Review saved.')) setReview(null); }}><h3>Review: {review.name}</h3><fieldset disabled={busy}><label>Decision<select name="decision"><option value="approve">Approve delivery</option><option value="revise">Request revisions</option></select></label><label>Feedback<textarea name="feedback" maxLength={4000} rows={4} defaultValue={review.mentor_feedback || ''} /></label><label>Score (0–100, optional)<input name="score" type="number" min={0} max={100} step={0.1} defaultValue={review.score ?? ''} /></label><button className="dash-button dash-button-primary" disabled={busy}>Save review</button><button type="button" className="dash-button" onClick={() => setReview(null)}>Cancel review</button></fieldset></form>}
      <div className="workspace-list">{shownTasks.length ? shownTasks.map(task => <article className="workspace-library-card workspace-milestone" id={`milestone-${task.id}`} key={task.id}><div className="workspace-actions"><h3>{task.name}</h3><span className="dash-status">{task.status || 'PENDING'}</span></div><p>{task.phase} · Due {task.due_date || 'not scheduled'}{task.start_date ? ` · Starts ${task.start_date}` : ''}</p>{task.description && <p className="workspace-notes">{task.description}</p>}{getDocuments([task]).map(item => <a className="dash-text-link workspace-document-link" key={item.id} href={item.url} target="_blank" rel="noreferrer">{item.name}<ExternalLink size={13} /></a>)}{(task.mentor_feedback || typeof task.score === 'number') && <div className="workspace-callout"><div><strong>Mentor feedback {typeof task.score === 'number' ? `· Score ${task.score}/100` : ''}</strong><p>{task.mentor_feedback || 'No written feedback added.'}</p></div></div>}<div className="workspace-actions"><button className="dash-button" disabled={busy || inactive || isComplete(task.status) || task.status === 'SUBMITTED' || isInactive(task.status)} onClick={() => { setMilestone(task); setReview(null); }}><Pencil size={14} />Edit & attach files</button>{isMentor && task.status === 'SUBMITTED' ? <button className="dash-button dash-button-primary" disabled={busy} onClick={() => { setReview(task); setMilestone(null); }}><CheckCircle2 size={14} />Review submission</button> : <button className="dash-button" disabled={busy || inactive || isComplete(task.status) || isInactive(task.status)} onClick={() => void mutate('milestone.submit', { milestoneId: task.id, withdraw: task.status === 'SUBMITTED' }, task.status === 'SUBMITTED' ? 'Submission withdrawn.' : 'Milestone submitted for review.')}>{task.status === 'SUBMITTED' ? 'Withdraw submission' : isComplete(task.status) ? 'Approved delivery' : 'Submit for review'}</button>}{owner && <button className="dash-button workspace-danger" disabled={busy} onClick={() => { if (window.confirm(`Delete milestone “${task.name}”?`)) void mutate('milestone.delete', { milestoneId: task.id }, 'Milestone deleted.'); }}><Trash2 size={14} />Delete</button>}</div></article>) : <p className="workspace-muted">{query ? 'No milestones match your search.' : 'Add milestones to plan your project.'}</p>}</div>
    </div></section>
  </div>;
}
