import { useState } from 'react';
import { CheckCircle2, ChevronRight, Clock3, GraduationCap, Link2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { DashboardData } from '../../lib/dashboard-data';
import { milestoneMatches, profileCompletion, projectHealth, sortMilestones } from '../../lib/workspace-insights';
import { RecordPager, WorkspaceSections } from './WorkspaceUI';

export default function WorkspaceInsights({ data, onEditProfile }: { data: DashboardData; onEditProfile: () => void }) {
  const [tab, setTab] = useState('priorities'); const [page, setPage] = useState(1);
  const health = projectHealth(data); const tasks = data.milestones.filter(task => health.some(item => item.project.id === task.squad_id));
  const overdue = tasks.filter(task => milestoneMatches(task, 'overdue')); const revisions = tasks.filter(task => milestoneMatches(task, 'revision')); const submitted = tasks.filter(task => milestoneMatches(task, 'submitted'));
  const profile = profileCompletion(data.profile); const unavailable = data.errors.some(error => ['Projects', 'Team projects', 'Milestones', 'Mentorship', 'Memberships'].includes(error.section));
  const priorities = sortMilestones(tasks.filter(task => milestoneMatches(task, 'overdue') || milestoneMatches(task, 'revision') || milestoneMatches(task, 'today'))).slice(0, 4);
  const currentPage = Math.min(page, Math.max(1, Math.ceil(health.length / 6)));
  return <WorkspaceSections label="Workspace insights" value={tab} onChange={setTab} sections={[
    { id: 'priorities', label: 'Priority signals', content: <div className="workspace-insights"><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Focus & next actions</h2><p>The deliveries that need your attention.</p></div><Clock3 size={18} /></div><div className="workspace-content">{unavailable ? <p className="workspace-muted">Refresh your workspace to load priority data.</p> : <><div className="workspace-focus-stats">{[[overdue.length, 'Overdue', 'overdue'], [revisions.length, 'Needs revision', 'revision'], [submitted.length, 'In review', 'submitted']].map(([count, label, filter]) => <Link key={String(filter)} to={`/dashboard/tasks?status=${filter}`}><strong>{count}</strong><span>{label}</span></Link>)}</div><div className="workspace-list">{priorities.length ? priorities.map(task => <Link className="workspace-priority" key={task.id} to={`/dashboard/projects/${encodeURIComponent(task.squad_id)}#milestone-${encodeURIComponent(task.id)}`}><div><strong>{task.name}</strong><small>{data.squads.find(project => project.id === task.squad_id)?.title} · {task.due_date || 'No due date'}</small></div><span className={milestoneMatches(task, 'overdue') ? 'dash-overdue' : 'workspace-muted'}>{milestoneMatches(task, 'revision') ? 'Revise delivery' : milestoneMatches(task, 'overdue') ? 'Overdue' : 'Due today'}</span><ChevronRight size={14} /></Link>) : <p className="workspace-muted">No overdue deliveries or revision requests.</p>}</div></>}</div></section><section className="dash-panel"><div className="dash-panel-heading"><div><h2>Workspace readiness</h2><p>Your next steps toward a complete academic record.</p></div><GraduationCap size={18} /></div><div className="workspace-content"><div className="workspace-readiness"><strong>{data.errors.some(error => error.section === 'Profile') ? '—' : `${profile.percent}%`}</strong><span>Profile complete</span><button className="dash-text-link" onClick={onEditProfile}>Update profile <ChevronRight size={13} /></button></div><div className="workspace-checklist">{[
      { done: data.squads.length > 0, label: 'Create a project workspace', path: 'projects' }, { done: data.milestones.length > 0, label: 'Plan your first milestone', path: 'tasks' }, { done: data.squads.some(item => item.mentor_id), label: 'Assign your project mentor', path: 'mentorship' }, { done: data.integrations.some(item => item.is_connected), label: 'Connect your project tools', path: 'integrations' },
    ].map(item => <Link key={item.path} to={`/dashboard/${item.path}`}>{item.done ? <CheckCircle2 size={16} /> : <Link2 size={16} />}<span>{item.label}</span><small>{item.done ? 'Ready' : 'Set up'}</small></Link>)}</div></div></section></div> },
    { id: 'health', label: 'Project health', count: health.length, content: <section className="dash-panel"><div className="dash-panel-heading"><div><h2>Project health</h2><p>Delivery progress and project-specific signals.</p></div><Link className="dash-text-link" to="/dashboard/projects">All projects <ChevronRight size={14} /></Link></div><div className="workspace-content workspace-health-grid">{unavailable ? <p className="workspace-muted">Project health is unavailable. Refresh your workspace.</p> : health.slice((currentPage - 1) * 6, currentPage * 6).map(item => <Link className="workspace-health-card" key={item.project.id} to={`/dashboard/projects/${encodeURIComponent(item.project.id)}`}><strong>{item.project.title}</strong><span>{item.overdue ? `${item.overdue} overdue` : item.revisions ? `${item.revisions} needs revision` : item.submitted ? `${item.submitted} awaiting review` : item.tasks ? 'Deliveries on track' : 'Add your project plan'}</span><div className="dash-progress"><span style={{ width: `${item.completion}%` }} /></div><small>{item.completion}% completed · {item.tasks} milestones</small></Link>)}</div><RecordPager page={currentPage} total={health.length} size={6} onChange={setPage} noun="projects" /></section> },
  ]} />;
}
